/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as ViajesPorMesZaragozaRouteImport } from './app/viajes-por-mes-zaragoza'
import { Route as ViajesPorDiaZaragozaRouteImport } from './app/viajes-por-dia-zaragoza'
import { Route as UsoBiziPorHoraRouteImport } from './app/uso-bizi-por-hora'
import { Route as UsoBiziPorEstacionRouteImport } from './app/uso-bizi-por-estacion'
import { Route as RegisterRouteImport } from './app/register'
import { Route as RedistribucionBiziZaragozaRouteImport } from './app/redistribucion-bizi-zaragoza'
import { Route as RankingEstacionesBiziRouteImport } from './app/ranking-estaciones-bizi'
import { Route as ProfileRouteImport } from './app/profile'
import { Route as MetodologiaRouteImport } from './app/metodologia'
import { Route as MapaEstacionesBiziZaragozaRouteImport } from './app/mapa-estaciones-bizi-zaragoza'
import { Route as LoginRouteImport } from './app/login'
import { Route as InformesMensualesBiziZaragozaRouteImport } from './app/informes-mensuales-bizi-zaragoza'
import { Route as InformesRouteImport } from './app/informes'
import { Route as ExplorarRouteImport } from './app/explorar'
import { Route as EstadoRouteImport } from './app/estado'
import { Route as EstadisticasBiziZaragozaRouteImport } from './app/estadisticas-bizi-zaragoza'
import { Route as EstacionesMasUsadasZaragozaRouteImport } from './app/estaciones-mas-usadas-zaragoza'
import { Route as EstacionesConMasBicisRouteImport } from './app/estaciones-con-mas-bicis'
import { Route as DevelopersRouteImport } from './app/developers'
import { Route as DashboardRouteImport } from './app/dashboard'
import { Route as CompararRouteImport } from './app/comparar'
import { Route as BiciradarRouteImport } from './app/biciradar'
import { Route as BetaRouteImport } from './app/beta'
import { Route as BarriosBiziZaragozaRouteImport } from './app/barrios-bizi-zaragoza'
import { Route as AboutRouteImport } from './app/about'
import { Route as IndexRouteImport } from './app/index'
import { Route as DashboardStatusRouteImport } from './app/dashboard/status'
import { Route as DashboardRedistribucionRouteImport } from './app/dashboard/redistribucion'
import { Route as DashboardFlujoRouteImport } from './app/dashboard/flujo'
import { Route as DashboardEstacionesRouteImport } from './app/dashboard/estaciones'
import { Route as DashboardConclusionesRouteImport } from './app/dashboard/conclusiones'
import { Route as DashboardAyudaRouteImport } from './app/dashboard/ayuda'
import { Route as DashboardAlertasRouteImport } from './app/dashboard/alertas'
import { Route as ApiStatusRouteImport } from './app/api/status'
import { Route as ApiStationsRouteImport } from './app/api/stations'
import { Route as ApiRankingsRouteImport } from './app/api/rankings'
import { Route as ApiAlertsRouteImport } from './app/api/alerts'
import { Route as InformesChar91monthChar93RouteRouteImport } from './app/informes/[month]/route'
import { Route as ApiHealthReadyRouteImport } from './app/api/health/ready'
import { Route as ApiHealthLiveRouteImport } from './app/api/health/live'
import { Route as DashboardViewsChar91modeChar93RouteRouteImport } from './app/dashboard/views/[mode]/route'
import { Route as DashboardEstacionesChar91stationIdChar93RouteRouteImport } from './app/dashboard/estaciones/[stationId]/route'

const ViajesPorMesZaragozaRoute = ViajesPorMesZaragozaRouteImport.update({
  id: '/viajes-por-mes-zaragoza',
  path: '/viajes-por-mes-zaragoza',
  getParentRoute: () => rootRouteImport,
} as any)
const ViajesPorDiaZaragozaRoute = ViajesPorDiaZaragozaRouteImport.update({
  id: '/viajes-por-dia-zaragoza',
  path: '/viajes-por-dia-zaragoza',
  getParentRoute: () => rootRouteImport,
} as any)
const UsoBiziPorHoraRoute = UsoBiziPorHoraRouteImport.update({
  id: '/uso-bizi-por-hora',
  path: '/uso-bizi-por-hora',
  getParentRoute: () => rootRouteImport,
} as any)
const UsoBiziPorEstacionRoute = UsoBiziPorEstacionRouteImport.update({
  id: '/uso-bizi-por-estacion',
  path: '/uso-bizi-por-estacion',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RedistribucionBiziZaragozaRoute =
  RedistribucionBiziZaragozaRouteImport.update({
    id: '/redistribucion-bizi-zaragoza',
    path: '/redistribucion-bizi-zaragoza',
    getParentRoute: () => rootRouteImport,
  } as any)
const RankingEstacionesBiziRoute = RankingEstacionesBiziRouteImport.update({
  id: '/ranking-estaciones-bizi',
  path: '/ranking-estaciones-bizi',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodologiaRoute = MetodologiaRouteImport.update({
  id: '/metodologia',
  path: '/metodologia',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaEstacionesBiziZaragozaRoute =
  MapaEstacionesBiziZaragozaRouteImport.update({
    id: '/mapa-estaciones-bizi-zaragoza',
    path: '/mapa-estaciones-bizi-zaragoza',
    getParentRoute: () => rootRouteImport,
  } as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InformesMensualesBiziZaragozaRoute =
  InformesMensualesBiziZaragozaRouteImport.update({
    id: '/informes-mensuales-bizi-zaragoza',
    path: '/informes-mensuales-bizi-zaragoza',
    getParentRoute: () => rootRouteImport,
  } as any)
const InformesRoute = InformesRouteImport.update({
  id: '/informes',
  path: '/informes',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const EstadoRoute = EstadoRouteImport.update({
  id: '/estado',
  path: '/estado',
  getParentRoute: () => rootRouteImport,
} as any)
const EstadisticasBiziZaragozaRoute =
  EstadisticasBiziZaragozaRouteImport.update({
    id: '/estadisticas-bizi-zaragoza',
    path: '/estadisticas-bizi-zaragoza',
    getParentRoute: () => rootRouteImport,
  } as any)
const EstacionesMasUsadasZaragozaRoute =
  EstacionesMasUsadasZaragozaRouteImport.update({
    id: '/estaciones-mas-usadas-zaragoza',
    path: '/estaciones-mas-usadas-zaragoza',
    getParentRoute: () => rootRouteImport,
  } as any)
const EstacionesConMasBicisRoute = EstacionesConMasBicisRouteImport.update({
  id: '/estaciones-con-mas-bicis',
  path: '/estaciones-con-mas-bicis',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompararRoute = CompararRouteImport.update({
  id: '/comparar',
  path: '/comparar',
  getParentRoute: () => rootRouteImport,
} as any)
const BiciradarRoute = BiciradarRouteImport.update({
  id: '/biciradar',
  path: '/biciradar',
  getParentRoute: () => rootRouteImport,
} as any)
const BetaRoute = BetaRouteImport.update({
  id: '/beta',
  path: '/beta',
  getParentRoute: () => rootRouteImport,
} as any)
const BarriosBiziZaragozaRoute = BarriosBiziZaragozaRouteImport.update({
  id: '/barrios-bizi-zaragoza',
  path: '/barrios-bizi-zaragoza',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStatusRoute = DashboardStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRedistribucionRoute = DashboardRedistribucionRouteImport.update({
  id: '/redistribucion',
  path: '/redistribucion',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFlujoRoute = DashboardFlujoRouteImport.update({
  id: '/flujo',
  path: '/flujo',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEstacionesRoute = DashboardEstacionesRouteImport.update({
  id: '/estaciones',
  path: '/estaciones',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConclusionesRoute = DashboardConclusionesRouteImport.update({
  id: '/conclusiones',
  path: '/conclusiones',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAyudaRoute = DashboardAyudaRouteImport.update({
  id: '/ayuda',
  path: '/ayuda',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAlertasRoute = DashboardAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiStatusRoute = ApiStatusRouteImport.update({
  id: '/api/status',
  path: '/api/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStationsRoute = ApiStationsRouteImport.update({
  id: '/api/stations',
  path: '/api/stations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRankingsRoute = ApiRankingsRouteImport.update({
  id: '/api/rankings',
  path: '/api/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAlertsRoute = ApiAlertsRouteImport.update({
  id: '/api/alerts',
  path: '/api/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const InformesChar91monthChar93RouteRoute =
  InformesChar91monthChar93RouteRouteImport.update({
    id: '/month',
    path: '/month',
    getParentRoute: () => InformesRoute,
  } as any)
const ApiHealthReadyRoute = ApiHealthReadyRouteImport.update({
  id: '/api/health/ready',
  path: '/api/health/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthLiveRoute = ApiHealthLiveRouteImport.update({
  id: '/api/health/live',
  path: '/api/health/live',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardViewsChar91modeChar93RouteRoute =
  DashboardViewsChar91modeChar93RouteRouteImport.update({
    id: '/views/mode',
    path: '/views/mode',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardEstacionesChar91stationIdChar93RouteRoute =
  DashboardEstacionesChar91stationIdChar93RouteRouteImport.update({
    id: '/stationId',
    path: '/stationId',
    getParentRoute: () => DashboardEstacionesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/barrios-bizi-zaragoza': typeof BarriosBiziZaragozaRoute
  '/beta': typeof BetaRoute
  '/biciradar': typeof BiciradarRoute
  '/comparar': typeof CompararRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/developers': typeof DevelopersRoute
  '/estaciones-con-mas-bicis': typeof EstacionesConMasBicisRoute
  '/estaciones-mas-usadas-zaragoza': typeof EstacionesMasUsadasZaragozaRoute
  '/estadisticas-bizi-zaragoza': typeof EstadisticasBiziZaragozaRoute
  '/estado': typeof EstadoRoute
  '/explorar': typeof ExplorarRoute
  '/informes': typeof InformesRouteWithChildren
  '/informes-mensuales-bizi-zaragoza': typeof InformesMensualesBiziZaragozaRoute
  '/login': typeof LoginRoute
  '/mapa-estaciones-bizi-zaragoza': typeof MapaEstacionesBiziZaragozaRoute
  '/metodologia': typeof MetodologiaRoute
  '/profile': typeof ProfileRoute
  '/ranking-estaciones-bizi': typeof RankingEstacionesBiziRoute
  '/redistribucion-bizi-zaragoza': typeof RedistribucionBiziZaragozaRoute
  '/register': typeof RegisterRoute
  '/uso-bizi-por-estacion': typeof UsoBiziPorEstacionRoute
  '/uso-bizi-por-hora': typeof UsoBiziPorHoraRoute
  '/viajes-por-dia-zaragoza': typeof ViajesPorDiaZaragozaRoute
  '/viajes-por-mes-zaragoza': typeof ViajesPorMesZaragozaRoute
  '/informes/month': typeof InformesChar91monthChar93RouteRoute
  '/api/alerts': typeof ApiAlertsRoute
  '/api/rankings': typeof ApiRankingsRoute
  '/api/stations': typeof ApiStationsRoute
  '/api/status': typeof ApiStatusRoute
  '/dashboard/alertas': typeof DashboardAlertasRoute
  '/dashboard/ayuda': typeof DashboardAyudaRoute
  '/dashboard/conclusiones': typeof DashboardConclusionesRoute
  '/dashboard/estaciones': typeof DashboardEstacionesRouteWithChildren
  '/dashboard/flujo': typeof DashboardFlujoRoute
  '/dashboard/redistribucion': typeof DashboardRedistribucionRoute
  '/dashboard/status': typeof DashboardStatusRoute
  '/dashboard/estaciones/stationId': typeof DashboardEstacionesChar91stationIdChar93RouteRoute
  '/dashboard/views/mode': typeof DashboardViewsChar91modeChar93RouteRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/barrios-bizi-zaragoza': typeof BarriosBiziZaragozaRoute
  '/beta': typeof BetaRoute
  '/biciradar': typeof BiciradarRoute
  '/comparar': typeof CompararRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/developers': typeof DevelopersRoute
  '/estaciones-con-mas-bicis': typeof EstacionesConMasBicisRoute
  '/estaciones-mas-usadas-zaragoza': typeof EstacionesMasUsadasZaragozaRoute
  '/estadisticas-bizi-zaragoza': typeof EstadisticasBiziZaragozaRoute
  '/estado': typeof EstadoRoute
  '/explorar': typeof ExplorarRoute
  '/informes': typeof InformesRouteWithChildren
  '/informes-mensuales-bizi-zaragoza': typeof InformesMensualesBiziZaragozaRoute
  '/login': typeof LoginRoute
  '/mapa-estaciones-bizi-zaragoza': typeof MapaEstacionesBiziZaragozaRoute
  '/metodologia': typeof MetodologiaRoute
  '/profile': typeof ProfileRoute
  '/ranking-estaciones-bizi': typeof RankingEstacionesBiziRoute
  '/redistribucion-bizi-zaragoza': typeof RedistribucionBiziZaragozaRoute
  '/register': typeof RegisterRoute
  '/uso-bizi-por-estacion': typeof UsoBiziPorEstacionRoute
  '/uso-bizi-por-hora': typeof UsoBiziPorHoraRoute
  '/viajes-por-dia-zaragoza': typeof ViajesPorDiaZaragozaRoute
  '/viajes-por-mes-zaragoza': typeof ViajesPorMesZaragozaRoute
  '/informes/month': typeof InformesChar91monthChar93RouteRoute
  '/api/alerts': typeof ApiAlertsRoute
  '/api/rankings': typeof ApiRankingsRoute
  '/api/stations': typeof ApiStationsRoute
  '/api/status': typeof ApiStatusRoute
  '/dashboard/alertas': typeof DashboardAlertasRoute
  '/dashboard/ayuda': typeof DashboardAyudaRoute
  '/dashboard/conclusiones': typeof DashboardConclusionesRoute
  '/dashboard/estaciones': typeof DashboardEstacionesRouteWithChildren
  '/dashboard/flujo': typeof DashboardFlujoRoute
  '/dashboard/redistribucion': typeof DashboardRedistribucionRoute
  '/dashboard/status': typeof DashboardStatusRoute
  '/dashboard/estaciones/stationId': typeof DashboardEstacionesChar91stationIdChar93RouteRoute
  '/dashboard/views/mode': typeof DashboardViewsChar91modeChar93RouteRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/barrios-bizi-zaragoza': typeof BarriosBiziZaragozaRoute
  '/beta': typeof BetaRoute
  '/biciradar': typeof BiciradarRoute
  '/comparar': typeof CompararRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/developers': typeof DevelopersRoute
  '/estaciones-con-mas-bicis': typeof EstacionesConMasBicisRoute
  '/estaciones-mas-usadas-zaragoza': typeof EstacionesMasUsadasZaragozaRoute
  '/estadisticas-bizi-zaragoza': typeof EstadisticasBiziZaragozaRoute
  '/estado': typeof EstadoRoute
  '/explorar': typeof ExplorarRoute
  '/informes': typeof InformesRouteWithChildren
  '/informes-mensuales-bizi-zaragoza': typeof InformesMensualesBiziZaragozaRoute
  '/login': typeof LoginRoute
  '/mapa-estaciones-bizi-zaragoza': typeof MapaEstacionesBiziZaragozaRoute
  '/metodologia': typeof MetodologiaRoute
  '/profile': typeof ProfileRoute
  '/ranking-estaciones-bizi': typeof RankingEstacionesBiziRoute
  '/redistribucion-bizi-zaragoza': typeof RedistribucionBiziZaragozaRoute
  '/register': typeof RegisterRoute
  '/uso-bizi-por-estacion': typeof UsoBiziPorEstacionRoute
  '/uso-bizi-por-hora': typeof UsoBiziPorHoraRoute
  '/viajes-por-dia-zaragoza': typeof ViajesPorDiaZaragozaRoute
  '/viajes-por-mes-zaragoza': typeof ViajesPorMesZaragozaRoute
  '/informes/month': typeof InformesChar91monthChar93RouteRoute
  '/api/alerts': typeof ApiAlertsRoute
  '/api/rankings': typeof ApiRankingsRoute
  '/api/stations': typeof ApiStationsRoute
  '/api/status': typeof ApiStatusRoute
  '/dashboard/alertas': typeof DashboardAlertasRoute
  '/dashboard/ayuda': typeof DashboardAyudaRoute
  '/dashboard/conclusiones': typeof DashboardConclusionesRoute
  '/dashboard/estaciones': typeof DashboardEstacionesRouteWithChildren
  '/dashboard/flujo': typeof DashboardFlujoRoute
  '/dashboard/redistribucion': typeof DashboardRedistribucionRoute
  '/dashboard/status': typeof DashboardStatusRoute
  '/dashboard/estaciones/stationId': typeof DashboardEstacionesChar91stationIdChar93RouteRoute
  '/dashboard/views/mode': typeof DashboardViewsChar91modeChar93RouteRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/barrios-bizi-zaragoza'
    | '/beta'
    | '/biciradar'
    | '/comparar'
    | '/dashboard'
    | '/developers'
    | '/estaciones-con-mas-bicis'
    | '/estaciones-mas-usadas-zaragoza'
    | '/estadisticas-bizi-zaragoza'
    | '/estado'
    | '/explorar'
    | '/informes'
    | '/informes-mensuales-bizi-zaragoza'
    | '/login'
    | '/mapa-estaciones-bizi-zaragoza'
    | '/metodologia'
    | '/profile'
    | '/ranking-estaciones-bizi'
    | '/redistribucion-bizi-zaragoza'
    | '/register'
    | '/uso-bizi-por-estacion'
    | '/uso-bizi-por-hora'
    | '/viajes-por-dia-zaragoza'
    | '/viajes-por-mes-zaragoza'
    | '/informes/month'
    | '/api/alerts'
    | '/api/rankings'
    | '/api/stations'
    | '/api/status'
    | '/dashboard/alertas'
    | '/dashboard/ayuda'
    | '/dashboard/conclusiones'
    | '/dashboard/estaciones'
    | '/dashboard/flujo'
    | '/dashboard/redistribucion'
    | '/dashboard/status'
    | '/dashboard/estaciones/stationId'
    | '/dashboard/views/mode'
    | '/api/health/live'
    | '/api/health/ready'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/barrios-bizi-zaragoza'
    | '/beta'
    | '/biciradar'
    | '/comparar'
    | '/dashboard'
    | '/developers'
    | '/estaciones-con-mas-bicis'
    | '/estaciones-mas-usadas-zaragoza'
    | '/estadisticas-bizi-zaragoza'
    | '/estado'
    | '/explorar'
    | '/informes'
    | '/informes-mensuales-bizi-zaragoza'
    | '/login'
    | '/mapa-estaciones-bizi-zaragoza'
    | '/metodologia'
    | '/profile'
    | '/ranking-estaciones-bizi'
    | '/redistribucion-bizi-zaragoza'
    | '/register'
    | '/uso-bizi-por-estacion'
    | '/uso-bizi-por-hora'
    | '/viajes-por-dia-zaragoza'
    | '/viajes-por-mes-zaragoza'
    | '/informes/month'
    | '/api/alerts'
    | '/api/rankings'
    | '/api/stations'
    | '/api/status'
    | '/dashboard/alertas'
    | '/dashboard/ayuda'
    | '/dashboard/conclusiones'
    | '/dashboard/estaciones'
    | '/dashboard/flujo'
    | '/dashboard/redistribucion'
    | '/dashboard/status'
    | '/dashboard/estaciones/stationId'
    | '/dashboard/views/mode'
    | '/api/health/live'
    | '/api/health/ready'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/barrios-bizi-zaragoza'
    | '/beta'
    | '/biciradar'
    | '/comparar'
    | '/dashboard'
    | '/developers'
    | '/estaciones-con-mas-bicis'
    | '/estaciones-mas-usadas-zaragoza'
    | '/estadisticas-bizi-zaragoza'
    | '/estado'
    | '/explorar'
    | '/informes'
    | '/informes-mensuales-bizi-zaragoza'
    | '/login'
    | '/mapa-estaciones-bizi-zaragoza'
    | '/metodologia'
    | '/profile'
    | '/ranking-estaciones-bizi'
    | '/redistribucion-bizi-zaragoza'
    | '/register'
    | '/uso-bizi-por-estacion'
    | '/uso-bizi-por-hora'
    | '/viajes-por-dia-zaragoza'
    | '/viajes-por-mes-zaragoza'
    | '/informes/month'
    | '/api/alerts'
    | '/api/rankings'
    | '/api/stations'
    | '/api/status'
    | '/dashboard/alertas'
    | '/dashboard/ayuda'
    | '/dashboard/conclusiones'
    | '/dashboard/estaciones'
    | '/dashboard/flujo'
    | '/dashboard/redistribucion'
    | '/dashboard/status'
    | '/dashboard/estaciones/stationId'
    | '/dashboard/views/mode'
    | '/api/health/live'
    | '/api/health/ready'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BarriosBiziZaragozaRoute: typeof BarriosBiziZaragozaRoute
  BetaRoute: typeof BetaRoute
  BiciradarRoute: typeof BiciradarRoute
  CompararRoute: typeof CompararRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DevelopersRoute: typeof DevelopersRoute
  EstacionesConMasBicisRoute: typeof EstacionesConMasBicisRoute
  EstacionesMasUsadasZaragozaRoute: typeof EstacionesMasUsadasZaragozaRoute
  EstadisticasBiziZaragozaRoute: typeof EstadisticasBiziZaragozaRoute
  EstadoRoute: typeof EstadoRoute
  ExplorarRoute: typeof ExplorarRoute
  InformesRoute: typeof InformesRouteWithChildren
  InformesMensualesBiziZaragozaRoute: typeof InformesMensualesBiziZaragozaRoute
  LoginRoute: typeof LoginRoute
  MapaEstacionesBiziZaragozaRoute: typeof MapaEstacionesBiziZaragozaRoute
  MetodologiaRoute: typeof MetodologiaRoute
  ProfileRoute: typeof ProfileRoute
  RankingEstacionesBiziRoute: typeof RankingEstacionesBiziRoute
  RedistribucionBiziZaragozaRoute: typeof RedistribucionBiziZaragozaRoute
  RegisterRoute: typeof RegisterRoute
  UsoBiziPorEstacionRoute: typeof UsoBiziPorEstacionRoute
  UsoBiziPorHoraRoute: typeof UsoBiziPorHoraRoute
  ViajesPorDiaZaragozaRoute: typeof ViajesPorDiaZaragozaRoute
  ViajesPorMesZaragozaRoute: typeof ViajesPorMesZaragozaRoute
  ApiAlertsRoute: typeof ApiAlertsRoute
  ApiRankingsRoute: typeof ApiRankingsRoute
  ApiStationsRoute: typeof ApiStationsRoute
  ApiStatusRoute: typeof ApiStatusRoute
  ApiHealthLiveRoute: typeof ApiHealthLiveRoute
  ApiHealthReadyRoute: typeof ApiHealthReadyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/viajes-por-mes-zaragoza': {
      id: '/viajes-por-mes-zaragoza'
      path: '/viajes-por-mes-zaragoza'
      fullPath: '/viajes-por-mes-zaragoza'
      preLoaderRoute: typeof ViajesPorMesZaragozaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viajes-por-dia-zaragoza': {
      id: '/viajes-por-dia-zaragoza'
      path: '/viajes-por-dia-zaragoza'
      fullPath: '/viajes-por-dia-zaragoza'
      preLoaderRoute: typeof ViajesPorDiaZaragozaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uso-bizi-por-hora': {
      id: '/uso-bizi-por-hora'
      path: '/uso-bizi-por-hora'
      fullPath: '/uso-bizi-por-hora'
      preLoaderRoute: typeof UsoBiziPorHoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uso-bizi-por-estacion': {
      id: '/uso-bizi-por-estacion'
      path: '/uso-bizi-por-estacion'
      fullPath: '/uso-bizi-por-estacion'
      preLoaderRoute: typeof UsoBiziPorEstacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redistribucion-bizi-zaragoza': {
      id: '/redistribucion-bizi-zaragoza'
      path: '/redistribucion-bizi-zaragoza'
      fullPath: '/redistribucion-bizi-zaragoza'
      preLoaderRoute: typeof RedistribucionBiziZaragozaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking-estaciones-bizi': {
      id: '/ranking-estaciones-bizi'
      path: '/ranking-estaciones-bizi'
      fullPath: '/ranking-estaciones-bizi'
      preLoaderRoute: typeof RankingEstacionesBiziRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodologia': {
      id: '/metodologia'
      path: '/metodologia'
      fullPath: '/metodologia'
      preLoaderRoute: typeof MetodologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa-estaciones-bizi-zaragoza': {
      id: '/mapa-estaciones-bizi-zaragoza'
      path: '/mapa-estaciones-bizi-zaragoza'
      fullPath: '/mapa-estaciones-bizi-zaragoza'
      preLoaderRoute: typeof MapaEstacionesBiziZaragozaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informes-mensuales-bizi-zaragoza': {
      id: '/informes-mensuales-bizi-zaragoza'
      path: '/informes-mensuales-bizi-zaragoza'
      fullPath: '/informes-mensuales-bizi-zaragoza'
      preLoaderRoute: typeof InformesMensualesBiziZaragozaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informes': {
      id: '/informes'
      path: '/informes'
      fullPath: '/informes'
      preLoaderRoute: typeof InformesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estado': {
      id: '/estado'
      path: '/estado'
      fullPath: '/estado'
      preLoaderRoute: typeof EstadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estadisticas-bizi-zaragoza': {
      id: '/estadisticas-bizi-zaragoza'
      path: '/estadisticas-bizi-zaragoza'
      fullPath: '/estadisticas-bizi-zaragoza'
      preLoaderRoute: typeof EstadisticasBiziZaragozaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estaciones-mas-usadas-zaragoza': {
      id: '/estaciones-mas-usadas-zaragoza'
      path: '/estaciones-mas-usadas-zaragoza'
      fullPath: '/estaciones-mas-usadas-zaragoza'
      preLoaderRoute: typeof EstacionesMasUsadasZaragozaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estaciones-con-mas-bicis': {
      id: '/estaciones-con-mas-bicis'
      path: '/estaciones-con-mas-bicis'
      fullPath: '/estaciones-con-mas-bicis'
      preLoaderRoute: typeof EstacionesConMasBicisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparar': {
      id: '/comparar'
      path: '/comparar'
      fullPath: '/comparar'
      preLoaderRoute: typeof CompararRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biciradar': {
      id: '/biciradar'
      path: '/biciradar'
      fullPath: '/biciradar'
      preLoaderRoute: typeof BiciradarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beta': {
      id: '/beta'
      path: '/beta'
      fullPath: '/beta'
      preLoaderRoute: typeof BetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barrios-bizi-zaragoza': {
      id: '/barrios-bizi-zaragoza'
      path: '/barrios-bizi-zaragoza'
      fullPath: '/barrios-bizi-zaragoza'
      preLoaderRoute: typeof BarriosBiziZaragozaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/status': {
      id: '/dashboard/status'
      path: '/status'
      fullPath: '/dashboard/status'
      preLoaderRoute: typeof DashboardStatusRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/redistribucion': {
      id: '/dashboard/redistribucion'
      path: '/redistribucion'
      fullPath: '/dashboard/redistribucion'
      preLoaderRoute: typeof DashboardRedistribucionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/flujo': {
      id: '/dashboard/flujo'
      path: '/flujo'
      fullPath: '/dashboard/flujo'
      preLoaderRoute: typeof DashboardFlujoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/estaciones': {
      id: '/dashboard/estaciones'
      path: '/estaciones'
      fullPath: '/dashboard/estaciones'
      preLoaderRoute: typeof DashboardEstacionesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/conclusiones': {
      id: '/dashboard/conclusiones'
      path: '/conclusiones'
      fullPath: '/dashboard/conclusiones'
      preLoaderRoute: typeof DashboardConclusionesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ayuda': {
      id: '/dashboard/ayuda'
      path: '/ayuda'
      fullPath: '/dashboard/ayuda'
      preLoaderRoute: typeof DashboardAyudaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/alertas': {
      id: '/dashboard/alertas'
      path: '/alertas'
      fullPath: '/dashboard/alertas'
      preLoaderRoute: typeof DashboardAlertasRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/status': {
      id: '/api/status'
      path: '/api/status'
      fullPath: '/api/status'
      preLoaderRoute: typeof ApiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stations': {
      id: '/api/stations'
      path: '/api/stations'
      fullPath: '/api/stations'
      preLoaderRoute: typeof ApiStationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rankings': {
      id: '/api/rankings'
      path: '/api/rankings'
      fullPath: '/api/rankings'
      preLoaderRoute: typeof ApiRankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/alerts': {
      id: '/api/alerts'
      path: '/api/alerts'
      fullPath: '/api/alerts'
      preLoaderRoute: typeof ApiAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informes/month': {
      id: '/informes/month'
      path: '/month'
      fullPath: '/informes/month'
      preLoaderRoute: typeof InformesChar91monthChar93RouteRouteImport
      parentRoute: typeof InformesRoute
    }
    '/api/health/ready': {
      id: '/api/health/ready'
      path: '/api/health/ready'
      fullPath: '/api/health/ready'
      preLoaderRoute: typeof ApiHealthReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/live': {
      id: '/api/health/live'
      path: '/api/health/live'
      fullPath: '/api/health/live'
      preLoaderRoute: typeof ApiHealthLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/views/mode': {
      id: '/dashboard/views/mode'
      path: '/views/mode'
      fullPath: '/dashboard/views/mode'
      preLoaderRoute: typeof DashboardViewsChar91modeChar93RouteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/estaciones/stationId': {
      id: '/dashboard/estaciones/stationId'
      path: '/stationId'
      fullPath: '/dashboard/estaciones/stationId'
      preLoaderRoute: typeof DashboardEstacionesChar91stationIdChar93RouteRouteImport
      parentRoute: typeof DashboardEstacionesRoute
    }
  }
}

interface DashboardEstacionesRouteChildren {
  DashboardEstacionesChar91stationIdChar93RouteRoute: typeof DashboardEstacionesChar91stationIdChar93RouteRoute
}

const DashboardEstacionesRouteChildren: DashboardEstacionesRouteChildren = {
  DashboardEstacionesChar91stationIdChar93RouteRoute:
    DashboardEstacionesChar91stationIdChar93RouteRoute,
}

const DashboardEstacionesRouteWithChildren =
  DashboardEstacionesRoute._addFileChildren(DashboardEstacionesRouteChildren)

interface DashboardRouteChildren {
  DashboardAlertasRoute: typeof DashboardAlertasRoute
  DashboardAyudaRoute: typeof DashboardAyudaRoute
  DashboardConclusionesRoute: typeof DashboardConclusionesRoute
  DashboardEstacionesRoute: typeof DashboardEstacionesRouteWithChildren
  DashboardFlujoRoute: typeof DashboardFlujoRoute
  DashboardRedistribucionRoute: typeof DashboardRedistribucionRoute
  DashboardStatusRoute: typeof DashboardStatusRoute
  DashboardViewsChar91modeChar93RouteRoute: typeof DashboardViewsChar91modeChar93RouteRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAlertasRoute: DashboardAlertasRoute,
  DashboardAyudaRoute: DashboardAyudaRoute,
  DashboardConclusionesRoute: DashboardConclusionesRoute,
  DashboardEstacionesRoute: DashboardEstacionesRouteWithChildren,
  DashboardFlujoRoute: DashboardFlujoRoute,
  DashboardRedistribucionRoute: DashboardRedistribucionRoute,
  DashboardStatusRoute: DashboardStatusRoute,
  DashboardViewsChar91modeChar93RouteRoute:
    DashboardViewsChar91modeChar93RouteRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface InformesRouteChildren {
  InformesChar91monthChar93RouteRoute: typeof InformesChar91monthChar93RouteRoute
}

const InformesRouteChildren: InformesRouteChildren = {
  InformesChar91monthChar93RouteRoute: InformesChar91monthChar93RouteRoute,
}

const InformesRouteWithChildren = InformesRoute._addFileChildren(
  InformesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BarriosBiziZaragozaRoute: BarriosBiziZaragozaRoute,
  BetaRoute: BetaRoute,
  BiciradarRoute: BiciradarRoute,
  CompararRoute: CompararRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DevelopersRoute: DevelopersRoute,
  EstacionesConMasBicisRoute: EstacionesConMasBicisRoute,
  EstacionesMasUsadasZaragozaRoute: EstacionesMasUsadasZaragozaRoute,
  EstadisticasBiziZaragozaRoute: EstadisticasBiziZaragozaRoute,
  EstadoRoute: EstadoRoute,
  ExplorarRoute: ExplorarRoute,
  InformesRoute: InformesRouteWithChildren,
  InformesMensualesBiziZaragozaRoute: InformesMensualesBiziZaragozaRoute,
  LoginRoute: LoginRoute,
  MapaEstacionesBiziZaragozaRoute: MapaEstacionesBiziZaragozaRoute,
  MetodologiaRoute: MetodologiaRoute,
  ProfileRoute: ProfileRoute,
  RankingEstacionesBiziRoute: RankingEstacionesBiziRoute,
  RedistribucionBiziZaragozaRoute: RedistribucionBiziZaragozaRoute,
  RegisterRoute: RegisterRoute,
  UsoBiziPorEstacionRoute: UsoBiziPorEstacionRoute,
  UsoBiziPorHoraRoute: UsoBiziPorHoraRoute,
  ViajesPorDiaZaragozaRoute: ViajesPorDiaZaragozaRoute,
  ViajesPorMesZaragozaRoute: ViajesPorMesZaragozaRoute,
  ApiAlertsRoute: ApiAlertsRoute,
  ApiRankingsRoute: ApiRankingsRoute,
  ApiStationsRoute: ApiStationsRoute,
  ApiStatusRoute: ApiStatusRoute,
  ApiHealthLiveRoute: ApiHealthLiveRoute,
  ApiHealthReadyRoute: ApiHealthReadyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
