/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as ViajesPorMesZaragozaRouteImport } from './app/viajes-por-mes-zaragoza'
import { Route as ViajesPorDiaZaragozaRouteImport } from './app/viajes-por-dia-zaragoza'
import { Route as UsoBiziPorHoraRouteImport } from './app/uso-bizi-por-hora'
import { Route as UsoBiziPorEstacionRouteImport } from './app/uso-bizi-por-estacion'
import { Route as SitemapDotxmlRouteImport } from './app/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './app/robots[.]txt'
import { Route as RedistribucionRouteImport } from './app/redistribucion'
import { Route as RankingEstacionesBiziRouteImport } from './app/ranking-estaciones-bizi'
import { Route as MetodologiaRouteImport } from './app/metodologia'
import { Route as MapaEstacionesBiziZaragozaRouteImport } from './app/mapa-estaciones-bizi-zaragoza'
import { Route as ManifestDotjsonRouteImport } from './app/manifest[.]json'
import { Route as LlmsDottxtRouteImport } from './app/llms[.]txt'
import { Route as LlmsFullDottxtRouteImport } from './app/llms-full[.]txt'
import { Route as LlmDottxtRouteImport } from './app/llm[.]txt'
import { Route as LlmTxtRouteImport } from './app/llm-txt'
import { Route as InformesMensualesBiziZaragozaRouteImport } from './app/informes-mensuales-bizi-zaragoza'
import { Route as InformesRouteImport } from './app/informes'
import { Route as ExplorarRouteImport } from './app/explorar'
import { Route as EstadoRouteImport } from './app/estado'
import { Route as EstadisticasBiziZaragozaRouteImport } from './app/estadisticas-bizi-zaragoza'
import { Route as EstacionesMasUsadasZaragozaRouteImport } from './app/estaciones-mas-usadas-zaragoza'
import { Route as EstacionesConMasBicisRouteImport } from './app/estaciones-con-mas-bicis'
import { Route as DevelopersRouteImport } from './app/developers'
import { Route as CompararRouteImport } from './app/comparar'
import { Route as BiciradarRouteImport } from './app/biciradar'
import { Route as BarriosBiziZaragozaRouteImport } from './app/barrios-bizi-zaragoza'
import { Route as AboutRouteImport } from './app/about'
import { Route as SplatRouteImport } from './app/$'
import { Route as EstadisticasRouteRouteImport } from './app/estadisticas/route'
import { Route as DashboardRouteRouteImport } from './app/dashboard/route'
import { Route as IndexRouteImport } from './app/index'
import { Route as EstadisticasIndexRouteImport } from './app/estadisticas/index'
import { Route as DashboardIndexRouteImport } from './app/dashboard/index'
import { Route as InformesMonthRouteImport } from './app/informes.$month'
import { Route as EstadisticasViajesRouteImport } from './app/estadisticas/viajes'
import { Route as EstadisticasRedistribucionRouteImport } from './app/estadisticas/redistribucion'
import { Route as EstadisticasMapaRouteImport } from './app/estadisticas/mapa'
import { Route as EstadisticasHorariosRouteImport } from './app/estadisticas/horarios'
import { Route as EstacionesStationIdRouteImport } from './app/estaciones/$stationId'
import { Route as BarriosDistrictSlugRouteImport } from './app/barrios/$districtSlug'
import { Route as ApiVersionRouteImport } from './app/api/version'
import { Route as ApiOpenapiDotjsonRouteImport } from './app/api/openapi[.]json'
import { Route as EstadisticasEstacionesRouteRouteImport } from './app/estadisticas/estaciones/route'
import { Route as EstadisticasBarriosRouteRouteImport } from './app/estadisticas/barrios/route'
import { Route as EstadisticasEstacionesIndexRouteImport } from './app/estadisticas/estaciones/index'
import { Route as EstadisticasBarriosIndexRouteImport } from './app/estadisticas/barrios/index'
import { Route as DashboardStatusIndexRouteImport } from './app/dashboard/status/index'
import { Route as DashboardRedistribucionIndexRouteImport } from './app/dashboard/redistribucion/index'
import { Route as DashboardOperacionesIndexRouteImport } from './app/dashboard/operaciones/index'
import { Route as DashboardInvestigacionIndexRouteImport } from './app/dashboard/investigacion/index'
import { Route as DashboardFlujoIndexRouteImport } from './app/dashboard/flujo/index'
import { Route as DashboardEstacionesIndexRouteImport } from './app/dashboard/estaciones/index'
import { Route as DashboardDatosIndexRouteImport } from './app/dashboard/datos/index'
import { Route as DashboardConclusionesIndexRouteImport } from './app/dashboard/conclusiones/index'
import { Route as DashboardAyudaIndexRouteImport } from './app/dashboard/ayuda/index'
import { Route as DashboardAlertasIndexRouteImport } from './app/dashboard/alertas/index'
import { Route as ApiStatusIndexRouteImport } from './app/api/status/index'
import { Route as ApiStationsIndexRouteImport } from './app/api/stations/index'
import { Route as ApiRebalancingReportIndexRouteImport } from './app/api/rebalancing-report/index'
import { Route as ApiRankingsIndexRouteImport } from './app/api/rankings/index'
import { Route as ApiPredictionsIndexRouteImport } from './app/api/predictions/index'
import { Route as ApiPatternsIndexRouteImport } from './app/api/patterns/index'
import { Route as ApiMobilityIndexRouteImport } from './app/api/mobility/index'
import { Route as ApiHistoryIndexRouteImport } from './app/api/history/index'
import { Route as ApiHeatmapIndexRouteImport } from './app/api/heatmap/index'
import { Route as ApiHealthIndexRouteImport } from './app/api/health/index'
import { Route as ApiGeoIndexRouteImport } from './app/api/geo/index'
import { Route as ApiDocsIndexRouteImport } from './app/api/docs/index'
import { Route as ApiCollectIndexRouteImport } from './app/api/collect/index'
import { Route as ApiAppVersionsIndexRouteImport } from './app/api/app-versions/index'
import { Route as ApiAlertsIndexRouteImport } from './app/api/alerts/index'
import { Route as EstadisticasEstacionesStationIdRouteImport } from './app/estadisticas/estaciones/$stationId'
import { Route as EstadisticasBarriosDistrictSlugRouteImport } from './app/estadisticas/barrios/$districtSlug'
import { Route as DashboardViewsModeRouteImport } from './app/dashboard/views/$mode'
import { Route as DashboardEstacionesStationIdRouteImport } from './app/dashboard/estaciones/$stationId'
import { Route as ApiHealthReadyRouteImport } from './app/api/health/ready'
import { Route as ApiHealthLiveRouteImport } from './app/api/health/live'
import { Route as ApiAlertsHistoryRouteRouteImport } from './app/api/alerts/history/route'
import { Route as ApiTokenRefreshIndexRouteImport } from './app/api/token/refresh/index'
import { Route as ApiOpsSentryTestIndexRouteImport } from './app/api/ops/sentry-test/index'
import { Route as ApiInstallRegisterIndexRouteImport } from './app/api/install/register/index'
import { Route as ApiGeoSearchIndexRouteImport } from './app/api/geo/search/index'
import { Route as ApiGeoReverseIndexRouteImport } from './app/api/geo/reverse/index'

const ViajesPorMesZaragozaRoute = ViajesPorMesZaragozaRouteImport.update({
  id: '/viajes-por-mes-zaragoza',
  path: '/viajes-por-mes-zaragoza',
  getParentRoute: () => rootRouteImport,
} as any)
const ViajesPorDiaZaragozaRoute = ViajesPorDiaZaragozaRouteImport.update({
  id: '/viajes-por-dia-zaragoza',
  path: '/viajes-por-dia-zaragoza',
  getParentRoute: () => rootRouteImport,
} as any)
const UsoBiziPorHoraRoute = UsoBiziPorHoraRouteImport.update({
  id: '/uso-bizi-por-hora',
  path: '/uso-bizi-por-hora',
  getParentRoute: () => rootRouteImport,
} as any)
const UsoBiziPorEstacionRoute = UsoBiziPorEstacionRouteImport.update({
  id: '/uso-bizi-por-estacion',
  path: '/uso-bizi-por-estacion',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RedistribucionRoute = RedistribucionRouteImport.update({
  id: '/redistribucion',
  path: '/redistribucion',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingEstacionesBiziRoute = RankingEstacionesBiziRouteImport.update({
  id: '/ranking-estaciones-bizi',
  path: '/ranking-estaciones-bizi',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodologiaRoute = MetodologiaRouteImport.update({
  id: '/metodologia',
  path: '/metodologia',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaEstacionesBiziZaragozaRoute =
  MapaEstacionesBiziZaragozaRouteImport.update({
    id: '/mapa-estaciones-bizi-zaragoza',
    path: '/mapa-estaciones-bizi-zaragoza',
    getParentRoute: () => rootRouteImport,
  } as any)
const ManifestDotjsonRoute = ManifestDotjsonRouteImport.update({
  id: '/manifest.json',
  path: '/manifest.json',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmDottxtRoute = LlmDottxtRouteImport.update({
  id: '/llm.txt',
  path: '/llm.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmTxtRoute = LlmTxtRouteImport.update({
  id: '/llm-txt',
  path: '/llm-txt',
  getParentRoute: () => rootRouteImport,
} as any)
const InformesMensualesBiziZaragozaRoute =
  InformesMensualesBiziZaragozaRouteImport.update({
    id: '/informes-mensuales-bizi-zaragoza',
    path: '/informes-mensuales-bizi-zaragoza',
    getParentRoute: () => rootRouteImport,
  } as any)
const InformesRoute = InformesRouteImport.update({
  id: '/informes',
  path: '/informes',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const EstadoRoute = EstadoRouteImport.update({
  id: '/estado',
  path: '/estado',
  getParentRoute: () => rootRouteImport,
} as any)
const EstadisticasBiziZaragozaRoute =
  EstadisticasBiziZaragozaRouteImport.update({
    id: '/estadisticas-bizi-zaragoza',
    path: '/estadisticas-bizi-zaragoza',
    getParentRoute: () => rootRouteImport,
  } as any)
const EstacionesMasUsadasZaragozaRoute =
  EstacionesMasUsadasZaragozaRouteImport.update({
    id: '/estaciones-mas-usadas-zaragoza',
    path: '/estaciones-mas-usadas-zaragoza',
    getParentRoute: () => rootRouteImport,
  } as any)
const EstacionesConMasBicisRoute = EstacionesConMasBicisRouteImport.update({
  id: '/estaciones-con-mas-bicis',
  path: '/estaciones-con-mas-bicis',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const CompararRoute = CompararRouteImport.update({
  id: '/comparar',
  path: '/comparar',
  getParentRoute: () => rootRouteImport,
} as any)
const BiciradarRoute = BiciradarRouteImport.update({
  id: '/biciradar',
  path: '/biciradar',
  getParentRoute: () => rootRouteImport,
} as any)
const BarriosBiziZaragozaRoute = BarriosBiziZaragozaRouteImport.update({
  id: '/barrios-bizi-zaragoza',
  path: '/barrios-bizi-zaragoza',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const EstadisticasRouteRoute = EstadisticasRouteRouteImport.update({
  id: '/estadisticas',
  path: '/estadisticas',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EstadisticasIndexRoute = EstadisticasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EstadisticasRouteRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const InformesMonthRoute = InformesMonthRouteImport.update({
  id: '/$month',
  path: '/$month',
  getParentRoute: () => InformesRoute,
} as any)
const EstadisticasViajesRoute = EstadisticasViajesRouteImport.update({
  id: '/viajes',
  path: '/viajes',
  getParentRoute: () => EstadisticasRouteRoute,
} as any)
const EstadisticasRedistribucionRoute =
  EstadisticasRedistribucionRouteImport.update({
    id: '/redistribucion',
    path: '/redistribucion',
    getParentRoute: () => EstadisticasRouteRoute,
  } as any)
const EstadisticasMapaRoute = EstadisticasMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => EstadisticasRouteRoute,
} as any)
const EstadisticasHorariosRoute = EstadisticasHorariosRouteImport.update({
  id: '/horarios',
  path: '/horarios',
  getParentRoute: () => EstadisticasRouteRoute,
} as any)
const EstacionesStationIdRoute = EstacionesStationIdRouteImport.update({
  id: '/estaciones/$stationId',
  path: '/estaciones/$stationId',
  getParentRoute: () => rootRouteImport,
} as any)
const BarriosDistrictSlugRoute = BarriosDistrictSlugRouteImport.update({
  id: '/barrios/$districtSlug',
  path: '/barrios/$districtSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVersionRoute = ApiVersionRouteImport.update({
  id: '/api/version',
  path: '/api/version',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenapiDotjsonRoute = ApiOpenapiDotjsonRouteImport.update({
  id: '/api/openapi.json',
  path: '/api/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const EstadisticasEstacionesRouteRoute =
  EstadisticasEstacionesRouteRouteImport.update({
    id: '/estaciones',
    path: '/estaciones',
    getParentRoute: () => EstadisticasRouteRoute,
  } as any)
const EstadisticasBarriosRouteRoute =
  EstadisticasBarriosRouteRouteImport.update({
    id: '/barrios',
    path: '/barrios',
    getParentRoute: () => EstadisticasRouteRoute,
  } as any)
const EstadisticasEstacionesIndexRoute =
  EstadisticasEstacionesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => EstadisticasEstacionesRouteRoute,
  } as any)
const EstadisticasBarriosIndexRoute =
  EstadisticasBarriosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => EstadisticasBarriosRouteRoute,
  } as any)
const DashboardStatusIndexRoute = DashboardStatusIndexRouteImport.update({
  id: '/status/',
  path: '/status/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardRedistribucionIndexRoute =
  DashboardRedistribucionIndexRouteImport.update({
    id: '/redistribucion/',
    path: '/redistribucion/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardOperacionesIndexRoute =
  DashboardOperacionesIndexRouteImport.update({
    id: '/operaciones/',
    path: '/operaciones/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardInvestigacionIndexRoute =
  DashboardInvestigacionIndexRouteImport.update({
    id: '/investigacion/',
    path: '/investigacion/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardFlujoIndexRoute = DashboardFlujoIndexRouteImport.update({
  id: '/flujo/',
  path: '/flujo/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEstacionesIndexRoute =
  DashboardEstacionesIndexRouteImport.update({
    id: '/estaciones/',
    path: '/estaciones/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardDatosIndexRoute = DashboardDatosIndexRouteImport.update({
  id: '/datos/',
  path: '/datos/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardConclusionesIndexRoute =
  DashboardConclusionesIndexRouteImport.update({
    id: '/conclusiones/',
    path: '/conclusiones/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAyudaIndexRoute = DashboardAyudaIndexRouteImport.update({
  id: '/ayuda/',
  path: '/ayuda/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAlertasIndexRoute = DashboardAlertasIndexRouteImport.update({
  id: '/alertas/',
  path: '/alertas/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiStatusIndexRoute = ApiStatusIndexRouteImport.update({
  id: '/api/status/',
  path: '/api/status/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStationsIndexRoute = ApiStationsIndexRouteImport.update({
  id: '/api/stations/',
  path: '/api/stations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRebalancingReportIndexRoute =
  ApiRebalancingReportIndexRouteImport.update({
    id: '/api/rebalancing-report/',
    path: '/api/rebalancing-report/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiRankingsIndexRoute = ApiRankingsIndexRouteImport.update({
  id: '/api/rankings/',
  path: '/api/rankings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPredictionsIndexRoute = ApiPredictionsIndexRouteImport.update({
  id: '/api/predictions/',
  path: '/api/predictions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPatternsIndexRoute = ApiPatternsIndexRouteImport.update({
  id: '/api/patterns/',
  path: '/api/patterns/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobilityIndexRoute = ApiMobilityIndexRouteImport.update({
  id: '/api/mobility/',
  path: '/api/mobility/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryIndexRoute = ApiHistoryIndexRouteImport.update({
  id: '/api/history/',
  path: '/api/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHeatmapIndexRoute = ApiHeatmapIndexRouteImport.update({
  id: '/api/heatmap/',
  path: '/api/heatmap/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthIndexRoute = ApiHealthIndexRouteImport.update({
  id: '/api/health/',
  path: '/api/health/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeoIndexRoute = ApiGeoIndexRouteImport.update({
  id: '/api/geo/',
  path: '/api/geo/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsIndexRoute = ApiDocsIndexRouteImport.update({
  id: '/api/docs/',
  path: '/api/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCollectIndexRoute = ApiCollectIndexRouteImport.update({
  id: '/api/collect/',
  path: '/api/collect/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAppVersionsIndexRoute = ApiAppVersionsIndexRouteImport.update({
  id: '/api/app-versions/',
  path: '/api/app-versions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAlertsIndexRoute = ApiAlertsIndexRouteImport.update({
  id: '/api/alerts/',
  path: '/api/alerts/',
  getParentRoute: () => rootRouteImport,
} as any)
const EstadisticasEstacionesStationIdRoute =
  EstadisticasEstacionesStationIdRouteImport.update({
    id: '/$stationId',
    path: '/$stationId',
    getParentRoute: () => EstadisticasEstacionesRouteRoute,
  } as any)
const EstadisticasBarriosDistrictSlugRoute =
  EstadisticasBarriosDistrictSlugRouteImport.update({
    id: '/$districtSlug',
    path: '/$districtSlug',
    getParentRoute: () => EstadisticasBarriosRouteRoute,
  } as any)
const DashboardViewsModeRoute = DashboardViewsModeRouteImport.update({
  id: '/views/$mode',
  path: '/views/$mode',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEstacionesStationIdRoute =
  DashboardEstacionesStationIdRouteImport.update({
    id: '/estaciones/$stationId',
    path: '/estaciones/$stationId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const ApiHealthReadyRoute = ApiHealthReadyRouteImport.update({
  id: '/api/health/ready',
  path: '/api/health/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthLiveRoute = ApiHealthLiveRouteImport.update({
  id: '/api/health/live',
  path: '/api/health/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAlertsHistoryRouteRoute = ApiAlertsHistoryRouteRouteImport.update({
  id: '/api/alerts/history',
  path: '/api/alerts/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTokenRefreshIndexRoute = ApiTokenRefreshIndexRouteImport.update({
  id: '/api/token/refresh/',
  path: '/api/token/refresh/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpsSentryTestIndexRoute = ApiOpsSentryTestIndexRouteImport.update({
  id: '/api/ops/sentry-test/',
  path: '/api/ops/sentry-test/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInstallRegisterIndexRoute = ApiInstallRegisterIndexRouteImport.update({
  id: '/api/install/register/',
  path: '/api/install/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeoSearchIndexRoute = ApiGeoSearchIndexRouteImport.update({
  id: '/api/geo/search/',
  path: '/api/geo/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeoReverseIndexRoute = ApiGeoReverseIndexRouteImport.update({
  id: '/api/geo/reverse/',
  path: '/api/geo/reverse/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/estadisticas': typeof EstadisticasRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/barrios-bizi-zaragoza': typeof BarriosBiziZaragozaRoute
  '/biciradar': typeof BiciradarRoute
  '/comparar': typeof CompararRoute
  '/developers': typeof DevelopersRoute
  '/estaciones-con-mas-bicis': typeof EstacionesConMasBicisRoute
  '/estaciones-mas-usadas-zaragoza': typeof EstacionesMasUsadasZaragozaRoute
  '/estadisticas-bizi-zaragoza': typeof EstadisticasBiziZaragozaRoute
  '/estado': typeof EstadoRoute
  '/explorar': typeof ExplorarRoute
  '/informes': typeof InformesRouteWithChildren
  '/informes-mensuales-bizi-zaragoza': typeof InformesMensualesBiziZaragozaRoute
  '/llm-txt': typeof LlmTxtRoute
  '/llm.txt': typeof LlmDottxtRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/manifest.json': typeof ManifestDotjsonRoute
  '/mapa-estaciones-bizi-zaragoza': typeof MapaEstacionesBiziZaragozaRoute
  '/metodologia': typeof MetodologiaRoute
  '/ranking-estaciones-bizi': typeof RankingEstacionesBiziRoute
  '/redistribucion': typeof RedistribucionRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/uso-bizi-por-estacion': typeof UsoBiziPorEstacionRoute
  '/uso-bizi-por-hora': typeof UsoBiziPorHoraRoute
  '/viajes-por-dia-zaragoza': typeof ViajesPorDiaZaragozaRoute
  '/viajes-por-mes-zaragoza': typeof ViajesPorMesZaragozaRoute
  '/estadisticas/barrios': typeof EstadisticasBarriosRouteRouteWithChildren
  '/estadisticas/estaciones': typeof EstadisticasEstacionesRouteRouteWithChildren
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/api/version': typeof ApiVersionRoute
  '/barrios/$districtSlug': typeof BarriosDistrictSlugRoute
  '/estaciones/$stationId': typeof EstacionesStationIdRoute
  '/estadisticas/horarios': typeof EstadisticasHorariosRoute
  '/estadisticas/mapa': typeof EstadisticasMapaRoute
  '/estadisticas/redistribucion': typeof EstadisticasRedistribucionRoute
  '/estadisticas/viajes': typeof EstadisticasViajesRoute
  '/informes/$month': typeof InformesMonthRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/estadisticas/': typeof EstadisticasIndexRoute
  '/api/alerts/history': typeof ApiAlertsHistoryRouteRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
  '/dashboard/estaciones/$stationId': typeof DashboardEstacionesStationIdRoute
  '/dashboard/views/$mode': typeof DashboardViewsModeRoute
  '/estadisticas/barrios/$districtSlug': typeof EstadisticasBarriosDistrictSlugRoute
  '/estadisticas/estaciones/$stationId': typeof EstadisticasEstacionesStationIdRoute
  '/api/alerts/': typeof ApiAlertsIndexRoute
  '/api/app-versions/': typeof ApiAppVersionsIndexRoute
  '/api/collect/': typeof ApiCollectIndexRoute
  '/api/docs/': typeof ApiDocsIndexRoute
  '/api/geo/': typeof ApiGeoIndexRoute
  '/api/health/': typeof ApiHealthIndexRoute
  '/api/heatmap/': typeof ApiHeatmapIndexRoute
  '/api/history/': typeof ApiHistoryIndexRoute
  '/api/mobility/': typeof ApiMobilityIndexRoute
  '/api/patterns/': typeof ApiPatternsIndexRoute
  '/api/predictions/': typeof ApiPredictionsIndexRoute
  '/api/rankings/': typeof ApiRankingsIndexRoute
  '/api/rebalancing-report/': typeof ApiRebalancingReportIndexRoute
  '/api/stations/': typeof ApiStationsIndexRoute
  '/api/status/': typeof ApiStatusIndexRoute
  '/dashboard/alertas/': typeof DashboardAlertasIndexRoute
  '/dashboard/ayuda/': typeof DashboardAyudaIndexRoute
  '/dashboard/conclusiones/': typeof DashboardConclusionesIndexRoute
  '/dashboard/datos/': typeof DashboardDatosIndexRoute
  '/dashboard/estaciones/': typeof DashboardEstacionesIndexRoute
  '/dashboard/flujo/': typeof DashboardFlujoIndexRoute
  '/dashboard/investigacion/': typeof DashboardInvestigacionIndexRoute
  '/dashboard/operaciones/': typeof DashboardOperacionesIndexRoute
  '/dashboard/redistribucion/': typeof DashboardRedistribucionIndexRoute
  '/dashboard/status/': typeof DashboardStatusIndexRoute
  '/estadisticas/barrios/': typeof EstadisticasBarriosIndexRoute
  '/estadisticas/estaciones/': typeof EstadisticasEstacionesIndexRoute
  '/api/geo/reverse/': typeof ApiGeoReverseIndexRoute
  '/api/geo/search/': typeof ApiGeoSearchIndexRoute
  '/api/install/register/': typeof ApiInstallRegisterIndexRoute
  '/api/ops/sentry-test/': typeof ApiOpsSentryTestIndexRoute
  '/api/token/refresh/': typeof ApiTokenRefreshIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/barrios-bizi-zaragoza': typeof BarriosBiziZaragozaRoute
  '/biciradar': typeof BiciradarRoute
  '/comparar': typeof CompararRoute
  '/developers': typeof DevelopersRoute
  '/estaciones-con-mas-bicis': typeof EstacionesConMasBicisRoute
  '/estaciones-mas-usadas-zaragoza': typeof EstacionesMasUsadasZaragozaRoute
  '/estadisticas-bizi-zaragoza': typeof EstadisticasBiziZaragozaRoute
  '/estado': typeof EstadoRoute
  '/explorar': typeof ExplorarRoute
  '/informes': typeof InformesRouteWithChildren
  '/informes-mensuales-bizi-zaragoza': typeof InformesMensualesBiziZaragozaRoute
  '/llm-txt': typeof LlmTxtRoute
  '/llm.txt': typeof LlmDottxtRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/manifest.json': typeof ManifestDotjsonRoute
  '/mapa-estaciones-bizi-zaragoza': typeof MapaEstacionesBiziZaragozaRoute
  '/metodologia': typeof MetodologiaRoute
  '/ranking-estaciones-bizi': typeof RankingEstacionesBiziRoute
  '/redistribucion': typeof RedistribucionRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/uso-bizi-por-estacion': typeof UsoBiziPorEstacionRoute
  '/uso-bizi-por-hora': typeof UsoBiziPorHoraRoute
  '/viajes-por-dia-zaragoza': typeof ViajesPorDiaZaragozaRoute
  '/viajes-por-mes-zaragoza': typeof ViajesPorMesZaragozaRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/api/version': typeof ApiVersionRoute
  '/barrios/$districtSlug': typeof BarriosDistrictSlugRoute
  '/estaciones/$stationId': typeof EstacionesStationIdRoute
  '/estadisticas/horarios': typeof EstadisticasHorariosRoute
  '/estadisticas/mapa': typeof EstadisticasMapaRoute
  '/estadisticas/redistribucion': typeof EstadisticasRedistribucionRoute
  '/estadisticas/viajes': typeof EstadisticasViajesRoute
  '/informes/$month': typeof InformesMonthRoute
  '/dashboard': typeof DashboardIndexRoute
  '/estadisticas': typeof EstadisticasIndexRoute
  '/api/alerts/history': typeof ApiAlertsHistoryRouteRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
  '/dashboard/estaciones/$stationId': typeof DashboardEstacionesStationIdRoute
  '/dashboard/views/$mode': typeof DashboardViewsModeRoute
  '/estadisticas/barrios/$districtSlug': typeof EstadisticasBarriosDistrictSlugRoute
  '/estadisticas/estaciones/$stationId': typeof EstadisticasEstacionesStationIdRoute
  '/api/alerts': typeof ApiAlertsIndexRoute
  '/api/app-versions': typeof ApiAppVersionsIndexRoute
  '/api/collect': typeof ApiCollectIndexRoute
  '/api/docs': typeof ApiDocsIndexRoute
  '/api/geo': typeof ApiGeoIndexRoute
  '/api/health': typeof ApiHealthIndexRoute
  '/api/heatmap': typeof ApiHeatmapIndexRoute
  '/api/history': typeof ApiHistoryIndexRoute
  '/api/mobility': typeof ApiMobilityIndexRoute
  '/api/patterns': typeof ApiPatternsIndexRoute
  '/api/predictions': typeof ApiPredictionsIndexRoute
  '/api/rankings': typeof ApiRankingsIndexRoute
  '/api/rebalancing-report': typeof ApiRebalancingReportIndexRoute
  '/api/stations': typeof ApiStationsIndexRoute
  '/api/status': typeof ApiStatusIndexRoute
  '/dashboard/alertas': typeof DashboardAlertasIndexRoute
  '/dashboard/ayuda': typeof DashboardAyudaIndexRoute
  '/dashboard/conclusiones': typeof DashboardConclusionesIndexRoute
  '/dashboard/datos': typeof DashboardDatosIndexRoute
  '/dashboard/estaciones': typeof DashboardEstacionesIndexRoute
  '/dashboard/flujo': typeof DashboardFlujoIndexRoute
  '/dashboard/investigacion': typeof DashboardInvestigacionIndexRoute
  '/dashboard/operaciones': typeof DashboardOperacionesIndexRoute
  '/dashboard/redistribucion': typeof DashboardRedistribucionIndexRoute
  '/dashboard/status': typeof DashboardStatusIndexRoute
  '/estadisticas/barrios': typeof EstadisticasBarriosIndexRoute
  '/estadisticas/estaciones': typeof EstadisticasEstacionesIndexRoute
  '/api/geo/reverse': typeof ApiGeoReverseIndexRoute
  '/api/geo/search': typeof ApiGeoSearchIndexRoute
  '/api/install/register': typeof ApiInstallRegisterIndexRoute
  '/api/ops/sentry-test': typeof ApiOpsSentryTestIndexRoute
  '/api/token/refresh': typeof ApiTokenRefreshIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/estadisticas': typeof EstadisticasRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/barrios-bizi-zaragoza': typeof BarriosBiziZaragozaRoute
  '/biciradar': typeof BiciradarRoute
  '/comparar': typeof CompararRoute
  '/developers': typeof DevelopersRoute
  '/estaciones-con-mas-bicis': typeof EstacionesConMasBicisRoute
  '/estaciones-mas-usadas-zaragoza': typeof EstacionesMasUsadasZaragozaRoute
  '/estadisticas-bizi-zaragoza': typeof EstadisticasBiziZaragozaRoute
  '/estado': typeof EstadoRoute
  '/explorar': typeof ExplorarRoute
  '/informes': typeof InformesRouteWithChildren
  '/informes-mensuales-bizi-zaragoza': typeof InformesMensualesBiziZaragozaRoute
  '/llm-txt': typeof LlmTxtRoute
  '/llm.txt': typeof LlmDottxtRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/manifest.json': typeof ManifestDotjsonRoute
  '/mapa-estaciones-bizi-zaragoza': typeof MapaEstacionesBiziZaragozaRoute
  '/metodologia': typeof MetodologiaRoute
  '/ranking-estaciones-bizi': typeof RankingEstacionesBiziRoute
  '/redistribucion': typeof RedistribucionRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/uso-bizi-por-estacion': typeof UsoBiziPorEstacionRoute
  '/uso-bizi-por-hora': typeof UsoBiziPorHoraRoute
  '/viajes-por-dia-zaragoza': typeof ViajesPorDiaZaragozaRoute
  '/viajes-por-mes-zaragoza': typeof ViajesPorMesZaragozaRoute
  '/estadisticas/barrios': typeof EstadisticasBarriosRouteRouteWithChildren
  '/estadisticas/estaciones': typeof EstadisticasEstacionesRouteRouteWithChildren
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/api/version': typeof ApiVersionRoute
  '/barrios/$districtSlug': typeof BarriosDistrictSlugRoute
  '/estaciones/$stationId': typeof EstacionesStationIdRoute
  '/estadisticas/horarios': typeof EstadisticasHorariosRoute
  '/estadisticas/mapa': typeof EstadisticasMapaRoute
  '/estadisticas/redistribucion': typeof EstadisticasRedistribucionRoute
  '/estadisticas/viajes': typeof EstadisticasViajesRoute
  '/informes/$month': typeof InformesMonthRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/estadisticas/': typeof EstadisticasIndexRoute
  '/api/alerts/history': typeof ApiAlertsHistoryRouteRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
  '/dashboard/estaciones/$stationId': typeof DashboardEstacionesStationIdRoute
  '/dashboard/views/$mode': typeof DashboardViewsModeRoute
  '/estadisticas/barrios/$districtSlug': typeof EstadisticasBarriosDistrictSlugRoute
  '/estadisticas/estaciones/$stationId': typeof EstadisticasEstacionesStationIdRoute
  '/api/alerts/': typeof ApiAlertsIndexRoute
  '/api/app-versions/': typeof ApiAppVersionsIndexRoute
  '/api/collect/': typeof ApiCollectIndexRoute
  '/api/docs/': typeof ApiDocsIndexRoute
  '/api/geo/': typeof ApiGeoIndexRoute
  '/api/health/': typeof ApiHealthIndexRoute
  '/api/heatmap/': typeof ApiHeatmapIndexRoute
  '/api/history/': typeof ApiHistoryIndexRoute
  '/api/mobility/': typeof ApiMobilityIndexRoute
  '/api/patterns/': typeof ApiPatternsIndexRoute
  '/api/predictions/': typeof ApiPredictionsIndexRoute
  '/api/rankings/': typeof ApiRankingsIndexRoute
  '/api/rebalancing-report/': typeof ApiRebalancingReportIndexRoute
  '/api/stations/': typeof ApiStationsIndexRoute
  '/api/status/': typeof ApiStatusIndexRoute
  '/dashboard/alertas/': typeof DashboardAlertasIndexRoute
  '/dashboard/ayuda/': typeof DashboardAyudaIndexRoute
  '/dashboard/conclusiones/': typeof DashboardConclusionesIndexRoute
  '/dashboard/datos/': typeof DashboardDatosIndexRoute
  '/dashboard/estaciones/': typeof DashboardEstacionesIndexRoute
  '/dashboard/flujo/': typeof DashboardFlujoIndexRoute
  '/dashboard/investigacion/': typeof DashboardInvestigacionIndexRoute
  '/dashboard/operaciones/': typeof DashboardOperacionesIndexRoute
  '/dashboard/redistribucion/': typeof DashboardRedistribucionIndexRoute
  '/dashboard/status/': typeof DashboardStatusIndexRoute
  '/estadisticas/barrios/': typeof EstadisticasBarriosIndexRoute
  '/estadisticas/estaciones/': typeof EstadisticasEstacionesIndexRoute
  '/api/geo/reverse/': typeof ApiGeoReverseIndexRoute
  '/api/geo/search/': typeof ApiGeoSearchIndexRoute
  '/api/install/register/': typeof ApiInstallRegisterIndexRoute
  '/api/ops/sentry-test/': typeof ApiOpsSentryTestIndexRoute
  '/api/token/refresh/': typeof ApiTokenRefreshIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/estadisticas'
    | '/$'
    | '/about'
    | '/barrios-bizi-zaragoza'
    | '/biciradar'
    | '/comparar'
    | '/developers'
    | '/estaciones-con-mas-bicis'
    | '/estaciones-mas-usadas-zaragoza'
    | '/estadisticas-bizi-zaragoza'
    | '/estado'
    | '/explorar'
    | '/informes'
    | '/informes-mensuales-bizi-zaragoza'
    | '/llm-txt'
    | '/llm.txt'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/manifest.json'
    | '/mapa-estaciones-bizi-zaragoza'
    | '/metodologia'
    | '/ranking-estaciones-bizi'
    | '/redistribucion'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/uso-bizi-por-estacion'
    | '/uso-bizi-por-hora'
    | '/viajes-por-dia-zaragoza'
    | '/viajes-por-mes-zaragoza'
    | '/estadisticas/barrios'
    | '/estadisticas/estaciones'
    | '/api/openapi.json'
    | '/api/version'
    | '/barrios/$districtSlug'
    | '/estaciones/$stationId'
    | '/estadisticas/horarios'
    | '/estadisticas/mapa'
    | '/estadisticas/redistribucion'
    | '/estadisticas/viajes'
    | '/informes/$month'
    | '/dashboard/'
    | '/estadisticas/'
    | '/api/alerts/history'
    | '/api/health/live'
    | '/api/health/ready'
    | '/dashboard/estaciones/$stationId'
    | '/dashboard/views/$mode'
    | '/estadisticas/barrios/$districtSlug'
    | '/estadisticas/estaciones/$stationId'
    | '/api/alerts/'
    | '/api/app-versions/'
    | '/api/collect/'
    | '/api/docs/'
    | '/api/geo/'
    | '/api/health/'
    | '/api/heatmap/'
    | '/api/history/'
    | '/api/mobility/'
    | '/api/patterns/'
    | '/api/predictions/'
    | '/api/rankings/'
    | '/api/rebalancing-report/'
    | '/api/stations/'
    | '/api/status/'
    | '/dashboard/alertas/'
    | '/dashboard/ayuda/'
    | '/dashboard/conclusiones/'
    | '/dashboard/datos/'
    | '/dashboard/estaciones/'
    | '/dashboard/flujo/'
    | '/dashboard/investigacion/'
    | '/dashboard/operaciones/'
    | '/dashboard/redistribucion/'
    | '/dashboard/status/'
    | '/estadisticas/barrios/'
    | '/estadisticas/estaciones/'
    | '/api/geo/reverse/'
    | '/api/geo/search/'
    | '/api/install/register/'
    | '/api/ops/sentry-test/'
    | '/api/token/refresh/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/barrios-bizi-zaragoza'
    | '/biciradar'
    | '/comparar'
    | '/developers'
    | '/estaciones-con-mas-bicis'
    | '/estaciones-mas-usadas-zaragoza'
    | '/estadisticas-bizi-zaragoza'
    | '/estado'
    | '/explorar'
    | '/informes'
    | '/informes-mensuales-bizi-zaragoza'
    | '/llm-txt'
    | '/llm.txt'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/manifest.json'
    | '/mapa-estaciones-bizi-zaragoza'
    | '/metodologia'
    | '/ranking-estaciones-bizi'
    | '/redistribucion'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/uso-bizi-por-estacion'
    | '/uso-bizi-por-hora'
    | '/viajes-por-dia-zaragoza'
    | '/viajes-por-mes-zaragoza'
    | '/api/openapi.json'
    | '/api/version'
    | '/barrios/$districtSlug'
    | '/estaciones/$stationId'
    | '/estadisticas/horarios'
    | '/estadisticas/mapa'
    | '/estadisticas/redistribucion'
    | '/estadisticas/viajes'
    | '/informes/$month'
    | '/dashboard'
    | '/estadisticas'
    | '/api/alerts/history'
    | '/api/health/live'
    | '/api/health/ready'
    | '/dashboard/estaciones/$stationId'
    | '/dashboard/views/$mode'
    | '/estadisticas/barrios/$districtSlug'
    | '/estadisticas/estaciones/$stationId'
    | '/api/alerts'
    | '/api/app-versions'
    | '/api/collect'
    | '/api/docs'
    | '/api/geo'
    | '/api/health'
    | '/api/heatmap'
    | '/api/history'
    | '/api/mobility'
    | '/api/patterns'
    | '/api/predictions'
    | '/api/rankings'
    | '/api/rebalancing-report'
    | '/api/stations'
    | '/api/status'
    | '/dashboard/alertas'
    | '/dashboard/ayuda'
    | '/dashboard/conclusiones'
    | '/dashboard/datos'
    | '/dashboard/estaciones'
    | '/dashboard/flujo'
    | '/dashboard/investigacion'
    | '/dashboard/operaciones'
    | '/dashboard/redistribucion'
    | '/dashboard/status'
    | '/estadisticas/barrios'
    | '/estadisticas/estaciones'
    | '/api/geo/reverse'
    | '/api/geo/search'
    | '/api/install/register'
    | '/api/ops/sentry-test'
    | '/api/token/refresh'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/estadisticas'
    | '/$'
    | '/about'
    | '/barrios-bizi-zaragoza'
    | '/biciradar'
    | '/comparar'
    | '/developers'
    | '/estaciones-con-mas-bicis'
    | '/estaciones-mas-usadas-zaragoza'
    | '/estadisticas-bizi-zaragoza'
    | '/estado'
    | '/explorar'
    | '/informes'
    | '/informes-mensuales-bizi-zaragoza'
    | '/llm-txt'
    | '/llm.txt'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/manifest.json'
    | '/mapa-estaciones-bizi-zaragoza'
    | '/metodologia'
    | '/ranking-estaciones-bizi'
    | '/redistribucion'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/uso-bizi-por-estacion'
    | '/uso-bizi-por-hora'
    | '/viajes-por-dia-zaragoza'
    | '/viajes-por-mes-zaragoza'
    | '/estadisticas/barrios'
    | '/estadisticas/estaciones'
    | '/api/openapi.json'
    | '/api/version'
    | '/barrios/$districtSlug'
    | '/estaciones/$stationId'
    | '/estadisticas/horarios'
    | '/estadisticas/mapa'
    | '/estadisticas/redistribucion'
    | '/estadisticas/viajes'
    | '/informes/$month'
    | '/dashboard/'
    | '/estadisticas/'
    | '/api/alerts/history'
    | '/api/health/live'
    | '/api/health/ready'
    | '/dashboard/estaciones/$stationId'
    | '/dashboard/views/$mode'
    | '/estadisticas/barrios/$districtSlug'
    | '/estadisticas/estaciones/$stationId'
    | '/api/alerts/'
    | '/api/app-versions/'
    | '/api/collect/'
    | '/api/docs/'
    | '/api/geo/'
    | '/api/health/'
    | '/api/heatmap/'
    | '/api/history/'
    | '/api/mobility/'
    | '/api/patterns/'
    | '/api/predictions/'
    | '/api/rankings/'
    | '/api/rebalancing-report/'
    | '/api/stations/'
    | '/api/status/'
    | '/dashboard/alertas/'
    | '/dashboard/ayuda/'
    | '/dashboard/conclusiones/'
    | '/dashboard/datos/'
    | '/dashboard/estaciones/'
    | '/dashboard/flujo/'
    | '/dashboard/investigacion/'
    | '/dashboard/operaciones/'
    | '/dashboard/redistribucion/'
    | '/dashboard/status/'
    | '/estadisticas/barrios/'
    | '/estadisticas/estaciones/'
    | '/api/geo/reverse/'
    | '/api/geo/search/'
    | '/api/install/register/'
    | '/api/ops/sentry-test/'
    | '/api/token/refresh/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  EstadisticasRouteRoute: typeof EstadisticasRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  BarriosBiziZaragozaRoute: typeof BarriosBiziZaragozaRoute
  BiciradarRoute: typeof BiciradarRoute
  CompararRoute: typeof CompararRoute
  DevelopersRoute: typeof DevelopersRoute
  EstacionesConMasBicisRoute: typeof EstacionesConMasBicisRoute
  EstacionesMasUsadasZaragozaRoute: typeof EstacionesMasUsadasZaragozaRoute
  EstadisticasBiziZaragozaRoute: typeof EstadisticasBiziZaragozaRoute
  EstadoRoute: typeof EstadoRoute
  ExplorarRoute: typeof ExplorarRoute
  InformesRoute: typeof InformesRouteWithChildren
  InformesMensualesBiziZaragozaRoute: typeof InformesMensualesBiziZaragozaRoute
  LlmTxtRoute: typeof LlmTxtRoute
  LlmDottxtRoute: typeof LlmDottxtRoute
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  ManifestDotjsonRoute: typeof ManifestDotjsonRoute
  MapaEstacionesBiziZaragozaRoute: typeof MapaEstacionesBiziZaragozaRoute
  MetodologiaRoute: typeof MetodologiaRoute
  RankingEstacionesBiziRoute: typeof RankingEstacionesBiziRoute
  RedistribucionRoute: typeof RedistribucionRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UsoBiziPorEstacionRoute: typeof UsoBiziPorEstacionRoute
  UsoBiziPorHoraRoute: typeof UsoBiziPorHoraRoute
  ViajesPorDiaZaragozaRoute: typeof ViajesPorDiaZaragozaRoute
  ViajesPorMesZaragozaRoute: typeof ViajesPorMesZaragozaRoute
  ApiOpenapiDotjsonRoute: typeof ApiOpenapiDotjsonRoute
  ApiVersionRoute: typeof ApiVersionRoute
  BarriosDistrictSlugRoute: typeof BarriosDistrictSlugRoute
  EstacionesStationIdRoute: typeof EstacionesStationIdRoute
  ApiAlertsHistoryRouteRoute: typeof ApiAlertsHistoryRouteRoute
  ApiHealthLiveRoute: typeof ApiHealthLiveRoute
  ApiHealthReadyRoute: typeof ApiHealthReadyRoute
  ApiAlertsIndexRoute: typeof ApiAlertsIndexRoute
  ApiAppVersionsIndexRoute: typeof ApiAppVersionsIndexRoute
  ApiCollectIndexRoute: typeof ApiCollectIndexRoute
  ApiDocsIndexRoute: typeof ApiDocsIndexRoute
  ApiGeoIndexRoute: typeof ApiGeoIndexRoute
  ApiHealthIndexRoute: typeof ApiHealthIndexRoute
  ApiHeatmapIndexRoute: typeof ApiHeatmapIndexRoute
  ApiHistoryIndexRoute: typeof ApiHistoryIndexRoute
  ApiMobilityIndexRoute: typeof ApiMobilityIndexRoute
  ApiPatternsIndexRoute: typeof ApiPatternsIndexRoute
  ApiPredictionsIndexRoute: typeof ApiPredictionsIndexRoute
  ApiRankingsIndexRoute: typeof ApiRankingsIndexRoute
  ApiRebalancingReportIndexRoute: typeof ApiRebalancingReportIndexRoute
  ApiStationsIndexRoute: typeof ApiStationsIndexRoute
  ApiStatusIndexRoute: typeof ApiStatusIndexRoute
  ApiGeoReverseIndexRoute: typeof ApiGeoReverseIndexRoute
  ApiGeoSearchIndexRoute: typeof ApiGeoSearchIndexRoute
  ApiInstallRegisterIndexRoute: typeof ApiInstallRegisterIndexRoute
  ApiOpsSentryTestIndexRoute: typeof ApiOpsSentryTestIndexRoute
  ApiTokenRefreshIndexRoute: typeof ApiTokenRefreshIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/viajes-por-mes-zaragoza': {
      id: '/viajes-por-mes-zaragoza'
      path: '/viajes-por-mes-zaragoza'
      fullPath: '/viajes-por-mes-zaragoza'
      preLoaderRoute: typeof ViajesPorMesZaragozaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viajes-por-dia-zaragoza': {
      id: '/viajes-por-dia-zaragoza'
      path: '/viajes-por-dia-zaragoza'
      fullPath: '/viajes-por-dia-zaragoza'
      preLoaderRoute: typeof ViajesPorDiaZaragozaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uso-bizi-por-hora': {
      id: '/uso-bizi-por-hora'
      path: '/uso-bizi-por-hora'
      fullPath: '/uso-bizi-por-hora'
      preLoaderRoute: typeof UsoBiziPorHoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uso-bizi-por-estacion': {
      id: '/uso-bizi-por-estacion'
      path: '/uso-bizi-por-estacion'
      fullPath: '/uso-bizi-por-estacion'
      preLoaderRoute: typeof UsoBiziPorEstacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redistribucion': {
      id: '/redistribucion'
      path: '/redistribucion'
      fullPath: '/redistribucion'
      preLoaderRoute: typeof RedistribucionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking-estaciones-bizi': {
      id: '/ranking-estaciones-bizi'
      path: '/ranking-estaciones-bizi'
      fullPath: '/ranking-estaciones-bizi'
      preLoaderRoute: typeof RankingEstacionesBiziRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodologia': {
      id: '/metodologia'
      path: '/metodologia'
      fullPath: '/metodologia'
      preLoaderRoute: typeof MetodologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa-estaciones-bizi-zaragoza': {
      id: '/mapa-estaciones-bizi-zaragoza'
      path: '/mapa-estaciones-bizi-zaragoza'
      fullPath: '/mapa-estaciones-bizi-zaragoza'
      preLoaderRoute: typeof MapaEstacionesBiziZaragozaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.json': {
      id: '/manifest.json'
      path: '/manifest.json'
      fullPath: '/manifest.json'
      preLoaderRoute: typeof ManifestDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llm.txt': {
      id: '/llm.txt'
      path: '/llm.txt'
      fullPath: '/llm.txt'
      preLoaderRoute: typeof LlmDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llm-txt': {
      id: '/llm-txt'
      path: '/llm-txt'
      fullPath: '/llm-txt'
      preLoaderRoute: typeof LlmTxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informes-mensuales-bizi-zaragoza': {
      id: '/informes-mensuales-bizi-zaragoza'
      path: '/informes-mensuales-bizi-zaragoza'
      fullPath: '/informes-mensuales-bizi-zaragoza'
      preLoaderRoute: typeof InformesMensualesBiziZaragozaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informes': {
      id: '/informes'
      path: '/informes'
      fullPath: '/informes'
      preLoaderRoute: typeof InformesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estado': {
      id: '/estado'
      path: '/estado'
      fullPath: '/estado'
      preLoaderRoute: typeof EstadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estadisticas-bizi-zaragoza': {
      id: '/estadisticas-bizi-zaragoza'
      path: '/estadisticas-bizi-zaragoza'
      fullPath: '/estadisticas-bizi-zaragoza'
      preLoaderRoute: typeof EstadisticasBiziZaragozaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estaciones-mas-usadas-zaragoza': {
      id: '/estaciones-mas-usadas-zaragoza'
      path: '/estaciones-mas-usadas-zaragoza'
      fullPath: '/estaciones-mas-usadas-zaragoza'
      preLoaderRoute: typeof EstacionesMasUsadasZaragozaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estaciones-con-mas-bicis': {
      id: '/estaciones-con-mas-bicis'
      path: '/estaciones-con-mas-bicis'
      fullPath: '/estaciones-con-mas-bicis'
      preLoaderRoute: typeof EstacionesConMasBicisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparar': {
      id: '/comparar'
      path: '/comparar'
      fullPath: '/comparar'
      preLoaderRoute: typeof CompararRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biciradar': {
      id: '/biciradar'
      path: '/biciradar'
      fullPath: '/biciradar'
      preLoaderRoute: typeof BiciradarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barrios-bizi-zaragoza': {
      id: '/barrios-bizi-zaragoza'
      path: '/barrios-bizi-zaragoza'
      fullPath: '/barrios-bizi-zaragoza'
      preLoaderRoute: typeof BarriosBiziZaragozaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estadisticas': {
      id: '/estadisticas'
      path: '/estadisticas'
      fullPath: '/estadisticas'
      preLoaderRoute: typeof EstadisticasRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estadisticas/': {
      id: '/estadisticas/'
      path: '/'
      fullPath: '/estadisticas/'
      preLoaderRoute: typeof EstadisticasIndexRouteImport
      parentRoute: typeof EstadisticasRouteRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/informes/$month': {
      id: '/informes/$month'
      path: '/$month'
      fullPath: '/informes/$month'
      preLoaderRoute: typeof InformesMonthRouteImport
      parentRoute: typeof InformesRoute
    }
    '/estadisticas/viajes': {
      id: '/estadisticas/viajes'
      path: '/viajes'
      fullPath: '/estadisticas/viajes'
      preLoaderRoute: typeof EstadisticasViajesRouteImport
      parentRoute: typeof EstadisticasRouteRoute
    }
    '/estadisticas/redistribucion': {
      id: '/estadisticas/redistribucion'
      path: '/redistribucion'
      fullPath: '/estadisticas/redistribucion'
      preLoaderRoute: typeof EstadisticasRedistribucionRouteImport
      parentRoute: typeof EstadisticasRouteRoute
    }
    '/estadisticas/mapa': {
      id: '/estadisticas/mapa'
      path: '/mapa'
      fullPath: '/estadisticas/mapa'
      preLoaderRoute: typeof EstadisticasMapaRouteImport
      parentRoute: typeof EstadisticasRouteRoute
    }
    '/estadisticas/horarios': {
      id: '/estadisticas/horarios'
      path: '/horarios'
      fullPath: '/estadisticas/horarios'
      preLoaderRoute: typeof EstadisticasHorariosRouteImport
      parentRoute: typeof EstadisticasRouteRoute
    }
    '/estaciones/$stationId': {
      id: '/estaciones/$stationId'
      path: '/estaciones/$stationId'
      fullPath: '/estaciones/$stationId'
      preLoaderRoute: typeof EstacionesStationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barrios/$districtSlug': {
      id: '/barrios/$districtSlug'
      path: '/barrios/$districtSlug'
      fullPath: '/barrios/$districtSlug'
      preLoaderRoute: typeof BarriosDistrictSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/version': {
      id: '/api/version'
      path: '/api/version'
      fullPath: '/api/version'
      preLoaderRoute: typeof ApiVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openapi.json': {
      id: '/api/openapi.json'
      path: '/api/openapi.json'
      fullPath: '/api/openapi.json'
      preLoaderRoute: typeof ApiOpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estadisticas/estaciones': {
      id: '/estadisticas/estaciones'
      path: '/estaciones'
      fullPath: '/estadisticas/estaciones'
      preLoaderRoute: typeof EstadisticasEstacionesRouteRouteImport
      parentRoute: typeof EstadisticasRouteRoute
    }
    '/estadisticas/barrios': {
      id: '/estadisticas/barrios'
      path: '/barrios'
      fullPath: '/estadisticas/barrios'
      preLoaderRoute: typeof EstadisticasBarriosRouteRouteImport
      parentRoute: typeof EstadisticasRouteRoute
    }
    '/estadisticas/estaciones/': {
      id: '/estadisticas/estaciones/'
      path: '/'
      fullPath: '/estadisticas/estaciones/'
      preLoaderRoute: typeof EstadisticasEstacionesIndexRouteImport
      parentRoute: typeof EstadisticasEstacionesRouteRoute
    }
    '/estadisticas/barrios/': {
      id: '/estadisticas/barrios/'
      path: '/'
      fullPath: '/estadisticas/barrios/'
      preLoaderRoute: typeof EstadisticasBarriosIndexRouteImport
      parentRoute: typeof EstadisticasBarriosRouteRoute
    }
    '/dashboard/status/': {
      id: '/dashboard/status/'
      path: '/status'
      fullPath: '/dashboard/status/'
      preLoaderRoute: typeof DashboardStatusIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/redistribucion/': {
      id: '/dashboard/redistribucion/'
      path: '/redistribucion'
      fullPath: '/dashboard/redistribucion/'
      preLoaderRoute: typeof DashboardRedistribucionIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/operaciones/': {
      id: '/dashboard/operaciones/'
      path: '/operaciones'
      fullPath: '/dashboard/operaciones/'
      preLoaderRoute: typeof DashboardOperacionesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/investigacion/': {
      id: '/dashboard/investigacion/'
      path: '/investigacion'
      fullPath: '/dashboard/investigacion/'
      preLoaderRoute: typeof DashboardInvestigacionIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/flujo/': {
      id: '/dashboard/flujo/'
      path: '/flujo'
      fullPath: '/dashboard/flujo/'
      preLoaderRoute: typeof DashboardFlujoIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/estaciones/': {
      id: '/dashboard/estaciones/'
      path: '/estaciones'
      fullPath: '/dashboard/estaciones/'
      preLoaderRoute: typeof DashboardEstacionesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/datos/': {
      id: '/dashboard/datos/'
      path: '/datos'
      fullPath: '/dashboard/datos/'
      preLoaderRoute: typeof DashboardDatosIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/conclusiones/': {
      id: '/dashboard/conclusiones/'
      path: '/conclusiones'
      fullPath: '/dashboard/conclusiones/'
      preLoaderRoute: typeof DashboardConclusionesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/ayuda/': {
      id: '/dashboard/ayuda/'
      path: '/ayuda'
      fullPath: '/dashboard/ayuda/'
      preLoaderRoute: typeof DashboardAyudaIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/alertas/': {
      id: '/dashboard/alertas/'
      path: '/alertas'
      fullPath: '/dashboard/alertas/'
      preLoaderRoute: typeof DashboardAlertasIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/status/': {
      id: '/api/status/'
      path: '/api/status'
      fullPath: '/api/status/'
      preLoaderRoute: typeof ApiStatusIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stations/': {
      id: '/api/stations/'
      path: '/api/stations'
      fullPath: '/api/stations/'
      preLoaderRoute: typeof ApiStationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rebalancing-report/': {
      id: '/api/rebalancing-report/'
      path: '/api/rebalancing-report'
      fullPath: '/api/rebalancing-report/'
      preLoaderRoute: typeof ApiRebalancingReportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rankings/': {
      id: '/api/rankings/'
      path: '/api/rankings'
      fullPath: '/api/rankings/'
      preLoaderRoute: typeof ApiRankingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/predictions/': {
      id: '/api/predictions/'
      path: '/api/predictions'
      fullPath: '/api/predictions/'
      preLoaderRoute: typeof ApiPredictionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/patterns/': {
      id: '/api/patterns/'
      path: '/api/patterns'
      fullPath: '/api/patterns/'
      preLoaderRoute: typeof ApiPatternsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobility/': {
      id: '/api/mobility/'
      path: '/api/mobility'
      fullPath: '/api/mobility/'
      preLoaderRoute: typeof ApiMobilityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history/': {
      id: '/api/history/'
      path: '/api/history'
      fullPath: '/api/history/'
      preLoaderRoute: typeof ApiHistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/heatmap/': {
      id: '/api/heatmap/'
      path: '/api/heatmap'
      fullPath: '/api/heatmap/'
      preLoaderRoute: typeof ApiHeatmapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/': {
      id: '/api/health/'
      path: '/api/health'
      fullPath: '/api/health/'
      preLoaderRoute: typeof ApiHealthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/geo/': {
      id: '/api/geo/'
      path: '/api/geo'
      fullPath: '/api/geo/'
      preLoaderRoute: typeof ApiGeoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/docs/': {
      id: '/api/docs/'
      path: '/api/docs'
      fullPath: '/api/docs/'
      preLoaderRoute: typeof ApiDocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/collect/': {
      id: '/api/collect/'
      path: '/api/collect'
      fullPath: '/api/collect/'
      preLoaderRoute: typeof ApiCollectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/app-versions/': {
      id: '/api/app-versions/'
      path: '/api/app-versions'
      fullPath: '/api/app-versions/'
      preLoaderRoute: typeof ApiAppVersionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/alerts/': {
      id: '/api/alerts/'
      path: '/api/alerts'
      fullPath: '/api/alerts/'
      preLoaderRoute: typeof ApiAlertsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estadisticas/estaciones/$stationId': {
      id: '/estadisticas/estaciones/$stationId'
      path: '/$stationId'
      fullPath: '/estadisticas/estaciones/$stationId'
      preLoaderRoute: typeof EstadisticasEstacionesStationIdRouteImport
      parentRoute: typeof EstadisticasEstacionesRouteRoute
    }
    '/estadisticas/barrios/$districtSlug': {
      id: '/estadisticas/barrios/$districtSlug'
      path: '/$districtSlug'
      fullPath: '/estadisticas/barrios/$districtSlug'
      preLoaderRoute: typeof EstadisticasBarriosDistrictSlugRouteImport
      parentRoute: typeof EstadisticasBarriosRouteRoute
    }
    '/dashboard/views/$mode': {
      id: '/dashboard/views/$mode'
      path: '/views/$mode'
      fullPath: '/dashboard/views/$mode'
      preLoaderRoute: typeof DashboardViewsModeRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/estaciones/$stationId': {
      id: '/dashboard/estaciones/$stationId'
      path: '/estaciones/$stationId'
      fullPath: '/dashboard/estaciones/$stationId'
      preLoaderRoute: typeof DashboardEstacionesStationIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/health/ready': {
      id: '/api/health/ready'
      path: '/api/health/ready'
      fullPath: '/api/health/ready'
      preLoaderRoute: typeof ApiHealthReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/live': {
      id: '/api/health/live'
      path: '/api/health/live'
      fullPath: '/api/health/live'
      preLoaderRoute: typeof ApiHealthLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/alerts/history': {
      id: '/api/alerts/history'
      path: '/api/alerts/history'
      fullPath: '/api/alerts/history'
      preLoaderRoute: typeof ApiAlertsHistoryRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/token/refresh/': {
      id: '/api/token/refresh/'
      path: '/api/token/refresh'
      fullPath: '/api/token/refresh/'
      preLoaderRoute: typeof ApiTokenRefreshIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ops/sentry-test/': {
      id: '/api/ops/sentry-test/'
      path: '/api/ops/sentry-test'
      fullPath: '/api/ops/sentry-test/'
      preLoaderRoute: typeof ApiOpsSentryTestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/install/register/': {
      id: '/api/install/register/'
      path: '/api/install/register'
      fullPath: '/api/install/register/'
      preLoaderRoute: typeof ApiInstallRegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/geo/search/': {
      id: '/api/geo/search/'
      path: '/api/geo/search'
      fullPath: '/api/geo/search/'
      preLoaderRoute: typeof ApiGeoSearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/geo/reverse/': {
      id: '/api/geo/reverse/'
      path: '/api/geo/reverse'
      fullPath: '/api/geo/reverse/'
      preLoaderRoute: typeof ApiGeoReverseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardEstacionesStationIdRoute: typeof DashboardEstacionesStationIdRoute
  DashboardViewsModeRoute: typeof DashboardViewsModeRoute
  DashboardAlertasIndexRoute: typeof DashboardAlertasIndexRoute
  DashboardAyudaIndexRoute: typeof DashboardAyudaIndexRoute
  DashboardConclusionesIndexRoute: typeof DashboardConclusionesIndexRoute
  DashboardDatosIndexRoute: typeof DashboardDatosIndexRoute
  DashboardEstacionesIndexRoute: typeof DashboardEstacionesIndexRoute
  DashboardFlujoIndexRoute: typeof DashboardFlujoIndexRoute
  DashboardInvestigacionIndexRoute: typeof DashboardInvestigacionIndexRoute
  DashboardOperacionesIndexRoute: typeof DashboardOperacionesIndexRoute
  DashboardRedistribucionIndexRoute: typeof DashboardRedistribucionIndexRoute
  DashboardStatusIndexRoute: typeof DashboardStatusIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardEstacionesStationIdRoute: DashboardEstacionesStationIdRoute,
  DashboardViewsModeRoute: DashboardViewsModeRoute,
  DashboardAlertasIndexRoute: DashboardAlertasIndexRoute,
  DashboardAyudaIndexRoute: DashboardAyudaIndexRoute,
  DashboardConclusionesIndexRoute: DashboardConclusionesIndexRoute,
  DashboardDatosIndexRoute: DashboardDatosIndexRoute,
  DashboardEstacionesIndexRoute: DashboardEstacionesIndexRoute,
  DashboardFlujoIndexRoute: DashboardFlujoIndexRoute,
  DashboardInvestigacionIndexRoute: DashboardInvestigacionIndexRoute,
  DashboardOperacionesIndexRoute: DashboardOperacionesIndexRoute,
  DashboardRedistribucionIndexRoute: DashboardRedistribucionIndexRoute,
  DashboardStatusIndexRoute: DashboardStatusIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface EstadisticasBarriosRouteRouteChildren {
  EstadisticasBarriosDistrictSlugRoute: typeof EstadisticasBarriosDistrictSlugRoute
  EstadisticasBarriosIndexRoute: typeof EstadisticasBarriosIndexRoute
}

const EstadisticasBarriosRouteRouteChildren: EstadisticasBarriosRouteRouteChildren =
  {
    EstadisticasBarriosDistrictSlugRoute: EstadisticasBarriosDistrictSlugRoute,
    EstadisticasBarriosIndexRoute: EstadisticasBarriosIndexRoute,
  }

const EstadisticasBarriosRouteRouteWithChildren =
  EstadisticasBarriosRouteRoute._addFileChildren(
    EstadisticasBarriosRouteRouteChildren,
  )

interface EstadisticasEstacionesRouteRouteChildren {
  EstadisticasEstacionesStationIdRoute: typeof EstadisticasEstacionesStationIdRoute
  EstadisticasEstacionesIndexRoute: typeof EstadisticasEstacionesIndexRoute
}

const EstadisticasEstacionesRouteRouteChildren: EstadisticasEstacionesRouteRouteChildren =
  {
    EstadisticasEstacionesStationIdRoute: EstadisticasEstacionesStationIdRoute,
    EstadisticasEstacionesIndexRoute: EstadisticasEstacionesIndexRoute,
  }

const EstadisticasEstacionesRouteRouteWithChildren =
  EstadisticasEstacionesRouteRoute._addFileChildren(
    EstadisticasEstacionesRouteRouteChildren,
  )

interface EstadisticasRouteRouteChildren {
  EstadisticasBarriosRouteRoute: typeof EstadisticasBarriosRouteRouteWithChildren
  EstadisticasEstacionesRouteRoute: typeof EstadisticasEstacionesRouteRouteWithChildren
  EstadisticasHorariosRoute: typeof EstadisticasHorariosRoute
  EstadisticasMapaRoute: typeof EstadisticasMapaRoute
  EstadisticasRedistribucionRoute: typeof EstadisticasRedistribucionRoute
  EstadisticasViajesRoute: typeof EstadisticasViajesRoute
  EstadisticasIndexRoute: typeof EstadisticasIndexRoute
}

const EstadisticasRouteRouteChildren: EstadisticasRouteRouteChildren = {
  EstadisticasBarriosRouteRoute: EstadisticasBarriosRouteRouteWithChildren,
  EstadisticasEstacionesRouteRoute:
    EstadisticasEstacionesRouteRouteWithChildren,
  EstadisticasHorariosRoute: EstadisticasHorariosRoute,
  EstadisticasMapaRoute: EstadisticasMapaRoute,
  EstadisticasRedistribucionRoute: EstadisticasRedistribucionRoute,
  EstadisticasViajesRoute: EstadisticasViajesRoute,
  EstadisticasIndexRoute: EstadisticasIndexRoute,
}

const EstadisticasRouteRouteWithChildren =
  EstadisticasRouteRoute._addFileChildren(EstadisticasRouteRouteChildren)

interface InformesRouteChildren {
  InformesMonthRoute: typeof InformesMonthRoute
}

const InformesRouteChildren: InformesRouteChildren = {
  InformesMonthRoute: InformesMonthRoute,
}

const InformesRouteWithChildren = InformesRoute._addFileChildren(
  InformesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  EstadisticasRouteRoute: EstadisticasRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  BarriosBiziZaragozaRoute: BarriosBiziZaragozaRoute,
  BiciradarRoute: BiciradarRoute,
  CompararRoute: CompararRoute,
  DevelopersRoute: DevelopersRoute,
  EstacionesConMasBicisRoute: EstacionesConMasBicisRoute,
  EstacionesMasUsadasZaragozaRoute: EstacionesMasUsadasZaragozaRoute,
  EstadisticasBiziZaragozaRoute: EstadisticasBiziZaragozaRoute,
  EstadoRoute: EstadoRoute,
  ExplorarRoute: ExplorarRoute,
  InformesRoute: InformesRouteWithChildren,
  InformesMensualesBiziZaragozaRoute: InformesMensualesBiziZaragozaRoute,
  LlmTxtRoute: LlmTxtRoute,
  LlmDottxtRoute: LlmDottxtRoute,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  ManifestDotjsonRoute: ManifestDotjsonRoute,
  MapaEstacionesBiziZaragozaRoute: MapaEstacionesBiziZaragozaRoute,
  MetodologiaRoute: MetodologiaRoute,
  RankingEstacionesBiziRoute: RankingEstacionesBiziRoute,
  RedistribucionRoute: RedistribucionRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UsoBiziPorEstacionRoute: UsoBiziPorEstacionRoute,
  UsoBiziPorHoraRoute: UsoBiziPorHoraRoute,
  ViajesPorDiaZaragozaRoute: ViajesPorDiaZaragozaRoute,
  ViajesPorMesZaragozaRoute: ViajesPorMesZaragozaRoute,
  ApiOpenapiDotjsonRoute: ApiOpenapiDotjsonRoute,
  ApiVersionRoute: ApiVersionRoute,
  BarriosDistrictSlugRoute: BarriosDistrictSlugRoute,
  EstacionesStationIdRoute: EstacionesStationIdRoute,
  ApiAlertsHistoryRouteRoute: ApiAlertsHistoryRouteRoute,
  ApiHealthLiveRoute: ApiHealthLiveRoute,
  ApiHealthReadyRoute: ApiHealthReadyRoute,
  ApiAlertsIndexRoute: ApiAlertsIndexRoute,
  ApiAppVersionsIndexRoute: ApiAppVersionsIndexRoute,
  ApiCollectIndexRoute: ApiCollectIndexRoute,
  ApiDocsIndexRoute: ApiDocsIndexRoute,
  ApiGeoIndexRoute: ApiGeoIndexRoute,
  ApiHealthIndexRoute: ApiHealthIndexRoute,
  ApiHeatmapIndexRoute: ApiHeatmapIndexRoute,
  ApiHistoryIndexRoute: ApiHistoryIndexRoute,
  ApiMobilityIndexRoute: ApiMobilityIndexRoute,
  ApiPatternsIndexRoute: ApiPatternsIndexRoute,
  ApiPredictionsIndexRoute: ApiPredictionsIndexRoute,
  ApiRankingsIndexRoute: ApiRankingsIndexRoute,
  ApiRebalancingReportIndexRoute: ApiRebalancingReportIndexRoute,
  ApiStationsIndexRoute: ApiStationsIndexRoute,
  ApiStatusIndexRoute: ApiStatusIndexRoute,
  ApiGeoReverseIndexRoute: ApiGeoReverseIndexRoute,
  ApiGeoSearchIndexRoute: ApiGeoSearchIndexRoute,
  ApiInstallRegisterIndexRoute: ApiInstallRegisterIndexRoute,
  ApiOpsSentryTestIndexRoute: ApiOpsSentryTestIndexRoute,
  ApiTokenRefreshIndexRoute: ApiTokenRefreshIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
